
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true

max_width = 100
normalize_doc_attributes = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
format_macro_bodies = true
format_macro_matchers = true
comment_width = 100
normalize_comments = true
combine_control_expr = false
trailing_comma = "Never"
trailing_semicolon = false
