// automatically generated by rust-bindgen 0.69.4

pub const AL_INVALID: i32 = -1;
pub const AL_NONE: u32 = 0;
pub const AL_FALSE: u32 = 0;
pub const AL_TRUE: u32 = 1;
pub const AL_SOURCE_RELATIVE: u32 = 514;
pub const AL_CONE_INNER_ANGLE: u32 = 4097;
pub const AL_CONE_OUTER_ANGLE: u32 = 4098;
pub const AL_PITCH: u32 = 4099;
pub const AL_POSITION: u32 = 4100;
pub const AL_DIRECTION: u32 = 4101;
pub const AL_VELOCITY: u32 = 4102;
pub const AL_LOOPING: u32 = 4103;
pub const AL_BUFFER: u32 = 4105;
pub const AL_GAIN: u32 = 4106;
pub const AL_MIN_GAIN: u32 = 4109;
pub const AL_MAX_GAIN: u32 = 4110;
pub const AL_ORIENTATION: u32 = 4111;
pub const AL_SOURCE_STATE: u32 = 4112;
pub const AL_INITIAL: u32 = 4113;
pub const AL_PLAYING: u32 = 4114;
pub const AL_PAUSED: u32 = 4115;
pub const AL_STOPPED: u32 = 4116;
pub const AL_BUFFERS_QUEUED: u32 = 4117;
pub const AL_BUFFERS_PROCESSED: u32 = 4118;
pub const AL_REFERENCE_DISTANCE: u32 = 4128;
pub const AL_ROLLOFF_FACTOR: u32 = 4129;
pub const AL_CONE_OUTER_GAIN: u32 = 4130;
pub const AL_MAX_DISTANCE: u32 = 4131;
pub const AL_SEC_OFFSET: u32 = 4132;
pub const AL_SAMPLE_OFFSET: u32 = 4133;
pub const AL_BYTE_OFFSET: u32 = 4134;
pub const AL_SOURCE_TYPE: u32 = 4135;
pub const AL_STATIC: u32 = 4136;
pub const AL_STREAMING: u32 = 4137;
pub const AL_UNDETERMINED: u32 = 4144;
pub const AL_FORMAT_MONO8: u32 = 4352;
pub const AL_FORMAT_MONO16: u32 = 4353;
pub const AL_FORMAT_STEREO8: u32 = 4354;
pub const AL_FORMAT_STEREO16: u32 = 4355;
pub const AL_FREQUENCY: u32 = 8193;
pub const AL_BITS: u32 = 8194;
pub const AL_CHANNELS: u32 = 8195;
pub const AL_SIZE: u32 = 8196;
pub const AL_UNUSED: u32 = 8208;
pub const AL_PENDING: u32 = 8209;
pub const AL_PROCESSED: u32 = 8210;
pub const AL_NO_ERROR: u32 = 0;
pub const AL_INVALID_NAME: u32 = 40961;
pub const AL_INVALID_ENUM: u32 = 40962;
pub const AL_INVALID_VALUE: u32 = 40963;
pub const AL_INVALID_OPERATION: u32 = 40964;
pub const AL_OUT_OF_MEMORY: u32 = 40965;
pub const AL_VENDOR: u32 = 45057;
pub const AL_VERSION: u32 = 45058;
pub const AL_RENDERER: u32 = 45059;
pub const AL_EXTENSIONS: u32 = 45060;
pub const AL_DOPPLER_FACTOR: u32 = 49152;
pub const AL_DOPPLER_VELOCITY: u32 = 49153;
pub const AL_SPEED_OF_SOUND: u32 = 49155;
pub const AL_DISTANCE_MODEL: u32 = 53248;
pub const AL_INVERSE_DISTANCE: u32 = 53249;
pub const AL_INVERSE_DISTANCE_CLAMPED: u32 = 53250;
pub const AL_LINEAR_DISTANCE: u32 = 53251;
pub const AL_LINEAR_DISTANCE_CLAMPED: u32 = 53252;
pub const AL_EXPONENT_DISTANCE: u32 = 53253;
pub const AL_EXPONENT_DISTANCE_CLAMPED: u32 = 53254;
/// 8-bit boolean
pub type ALboolean = ::std::os::raw::c_char;
/// character
pub type ALchar = ::std::os::raw::c_char;
/// signed 8-bit integer
pub type ALbyte = ::std::os::raw::c_schar;
/// unsigned 8-bit integer
pub type ALubyte = ::std::os::raw::c_uchar;
/// signed 16-bit integer
pub type ALshort = ::std::os::raw::c_short;
/// unsigned 16-bit integer
pub type ALushort = ::std::os::raw::c_ushort;
/// signed 32-bit integer
pub type ALint = ::std::os::raw::c_int;
/// unsigned 32-bit integer
pub type ALuint = ::std::os::raw::c_uint;
/// non-negative 32-bit integer size
pub type ALsizei = ::std::os::raw::c_int;
/// 32-bit enumeration value
pub type ALenum = ::std::os::raw::c_int;
/// 32-bit IEEE-754 floating-point
pub type ALfloat = f32;
/// 64-bit IEEE-754 floating-point
pub type ALdouble = f64;
/// void type (opaque pointers only)
pub type ALvoid = ::std::os::raw::c_void;
extern "C" {
    pub fn alEnable(capability: ALenum);
    pub fn alDisable(capability: ALenum);
    pub fn alIsEnabled(capability: ALenum) -> ALboolean;
    pub fn alDopplerFactor(value: ALfloat);
    pub fn alDopplerVelocity(value: ALfloat);
    pub fn alSpeedOfSound(value: ALfloat);
    pub fn alDistanceModel(distanceModel: ALenum);
    pub fn alGetString(param: ALenum) -> *const ALchar;
    pub fn alGetBooleanv(param: ALenum, values: *mut ALboolean);
    pub fn alGetIntegerv(param: ALenum, values: *mut ALint);
    pub fn alGetFloatv(param: ALenum, values: *mut ALfloat);
    pub fn alGetDoublev(param: ALenum, values: *mut ALdouble);
    pub fn alGetBoolean(param: ALenum) -> ALboolean;
    pub fn alGetInteger(param: ALenum) -> ALint;
    pub fn alGetFloat(param: ALenum) -> ALfloat;
    pub fn alGetDouble(param: ALenum) -> ALdouble;
    /// Obtain the first error generated in the AL context since the last call to
    /// this function.
    pub fn alGetError() -> ALenum;
    /// Query for the presence of an extension on the AL context.
    pub fn alIsExtensionPresent(extname: *const ALchar) -> ALboolean;
    /// Retrieve the address of a function. The returned function may be context-
    /// specific.
    pub fn alGetProcAddress(fname: *const ALchar) -> *mut ::std::os::raw::c_void;
    /// Retrieve the value of an enum. The returned value may be context-specific.
    pub fn alGetEnumValue(ename: *const ALchar) -> ALenum;
    pub fn alListenerf(param: ALenum, value: ALfloat);
    pub fn alListener3f(param: ALenum, value1: ALfloat, value2: ALfloat, value3: ALfloat);
    pub fn alListenerfv(param: ALenum, values: *const ALfloat);
    pub fn alListeneri(param: ALenum, value: ALint);
    pub fn alListener3i(param: ALenum, value1: ALint, value2: ALint, value3: ALint);
    pub fn alListeneriv(param: ALenum, values: *const ALint);
    pub fn alGetListenerf(param: ALenum, value: *mut ALfloat);
    pub fn alGetListener3f(
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    );
    pub fn alGetListenerfv(param: ALenum, values: *mut ALfloat);
    pub fn alGetListeneri(param: ALenum, value: *mut ALint);
    pub fn alGetListener3i(
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    );
    pub fn alGetListeneriv(param: ALenum, values: *mut ALint);
    /// Create source objects.
    pub fn alGenSources(n: ALsizei, sources: *mut ALuint);
    /// Delete source objects.
    pub fn alDeleteSources(n: ALsizei, sources: *const ALuint);
    /// Verify an ID is for a valid source.
    pub fn alIsSource(source: ALuint) -> ALboolean;
    pub fn alSourcef(source: ALuint, param: ALenum, value: ALfloat);
    pub fn alSource3f(
        source: ALuint,
        param: ALenum,
        value1: ALfloat,
        value2: ALfloat,
        value3: ALfloat
    );
    pub fn alSourcefv(source: ALuint, param: ALenum, values: *const ALfloat);
    pub fn alSourcei(source: ALuint, param: ALenum, value: ALint);
    pub fn alSource3i(source: ALuint, param: ALenum, value1: ALint, value2: ALint, value3: ALint);
    pub fn alSourceiv(source: ALuint, param: ALenum, values: *const ALint);
    pub fn alGetSourcef(source: ALuint, param: ALenum, value: *mut ALfloat);
    pub fn alGetSource3f(
        source: ALuint,
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    );
    pub fn alGetSourcefv(source: ALuint, param: ALenum, values: *mut ALfloat);
    pub fn alGetSourcei(source: ALuint, param: ALenum, value: *mut ALint);
    pub fn alGetSource3i(
        source: ALuint,
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    );
    pub fn alGetSourceiv(source: ALuint, param: ALenum, values: *mut ALint);
    /// Play, restart, or resume a source, setting its state to AL_PLAYING.
    pub fn alSourcePlay(source: ALuint);
    /// Stop a source, setting its state to AL_STOPPED if playing or paused.
    pub fn alSourceStop(source: ALuint);
    /// Rewind a source, setting its state to AL_INITIAL.
    pub fn alSourceRewind(source: ALuint);
    /// Pause a source, setting its state to AL_PAUSED if playing.
    pub fn alSourcePause(source: ALuint);
    /// Play, restart, or resume a list of sources atomically.
    pub fn alSourcePlayv(n: ALsizei, sources: *const ALuint);
    /// Stop a list of sources atomically.
    pub fn alSourceStopv(n: ALsizei, sources: *const ALuint);
    /// Rewind a list of sources atomically.
    pub fn alSourceRewindv(n: ALsizei, sources: *const ALuint);
    /// Pause a list of sources atomically.
    pub fn alSourcePausev(n: ALsizei, sources: *const ALuint);
    /// Queue buffers onto a source
    pub fn alSourceQueueBuffers(source: ALuint, nb: ALsizei, buffers: *const ALuint);
    /// Unqueue processed buffers from a source
    pub fn alSourceUnqueueBuffers(source: ALuint, nb: ALsizei, buffers: *mut ALuint);
    /// Create buffer objects
    pub fn alGenBuffers(n: ALsizei, buffers: *mut ALuint);
    /// Delete buffer objects
    pub fn alDeleteBuffers(n: ALsizei, buffers: *const ALuint);
    /// Verify an ID is a valid buffer (including the NULL buffer)
    pub fn alIsBuffer(buffer: ALuint) -> ALboolean;
    /// Copies data into the buffer, interpreting it using the specified format and
    /// samplerate.
    pub fn alBufferData(
        buffer: ALuint,
        format: ALenum,
        data: *const ALvoid,
        size: ALsizei,
        samplerate: ALsizei
    );
    pub fn alBufferf(buffer: ALuint, param: ALenum, value: ALfloat);
    pub fn alBuffer3f(
        buffer: ALuint,
        param: ALenum,
        value1: ALfloat,
        value2: ALfloat,
        value3: ALfloat
    );
    pub fn alBufferfv(buffer: ALuint, param: ALenum, values: *const ALfloat);
    pub fn alBufferi(buffer: ALuint, param: ALenum, value: ALint);
    pub fn alBuffer3i(buffer: ALuint, param: ALenum, value1: ALint, value2: ALint, value3: ALint);
    pub fn alBufferiv(buffer: ALuint, param: ALenum, values: *const ALint);
    pub fn alGetBufferf(buffer: ALuint, param: ALenum, value: *mut ALfloat);
    pub fn alGetBuffer3f(
        buffer: ALuint,
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    );
    pub fn alGetBufferfv(buffer: ALuint, param: ALenum, values: *mut ALfloat);
    pub fn alGetBufferi(buffer: ALuint, param: ALenum, value: *mut ALint);
    pub fn alGetBuffer3i(
        buffer: ALuint,
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    );
    pub fn alGetBufferiv(buffer: ALuint, param: ALenum, values: *mut ALint);
}
pub type LPALENABLE = ::std::option::Option<unsafe extern "C" fn(capability: ALenum)>;
pub type LPALDISABLE = ::std::option::Option<unsafe extern "C" fn(capability: ALenum)>;
pub type LPALISENABLED =
    ::std::option::Option<unsafe extern "C" fn(capability: ALenum) -> ALboolean>;
pub type LPALGETSTRING =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> *const ALchar>;
pub type LPALGETBOOLEANV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALboolean)>;
pub type LPALGETINTEGERV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALint)>;
pub type LPALGETFLOATV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALfloat)>;
pub type LPALGETDOUBLEV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALdouble)>;
pub type LPALGETBOOLEAN = ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALboolean>;
pub type LPALGETINTEGER = ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALint>;
pub type LPALGETFLOAT = ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALfloat>;
pub type LPALGETDOUBLE = ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALdouble>;
pub type LPALGETERROR = ::std::option::Option<unsafe extern "C" fn() -> ALenum>;
pub type LPALISEXTENSIONPRESENT =
    ::std::option::Option<unsafe extern "C" fn(extname: *const ALchar) -> ALboolean>;
pub type LPALGETPROCADDRESS = ::std::option::Option<
    unsafe extern "C" fn(fname: *const ALchar) -> *mut ::std::os::raw::c_void
>;
pub type LPALGETENUMVALUE =
    ::std::option::Option<unsafe extern "C" fn(ename: *const ALchar) -> ALenum>;
pub type LPALLISTENERF = ::std::option::Option<unsafe extern "C" fn(param: ALenum, value: ALfloat)>;
pub type LPALLISTENER3F = ::std::option::Option<
    unsafe extern "C" fn(param: ALenum, value1: ALfloat, value2: ALfloat, value3: ALfloat)
>;
pub type LPALLISTENERFV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *const ALfloat)>;
pub type LPALLISTENERI = ::std::option::Option<unsafe extern "C" fn(param: ALenum, value: ALint)>;
pub type LPALLISTENER3I = ::std::option::Option<
    unsafe extern "C" fn(param: ALenum, value1: ALint, value2: ALint, value3: ALint)
>;
pub type LPALLISTENERIV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *const ALint)>;
pub type LPALGETLISTENERF =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, value: *mut ALfloat)>;
pub type LPALGETLISTENER3F = ::std::option::Option<
    unsafe extern "C" fn(
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    )
>;
pub type LPALGETLISTENERFV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALfloat)>;
pub type LPALGETLISTENERI =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, value: *mut ALint)>;
pub type LPALGETLISTENER3I = ::std::option::Option<
    unsafe extern "C" fn(param: ALenum, value1: *mut ALint, value2: *mut ALint, value3: *mut ALint)
>;
pub type LPALGETLISTENERIV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALint)>;
pub type LPALGENSOURCES =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *mut ALuint)>;
pub type LPALDELETESOURCES =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALISSOURCE = ::std::option::Option<unsafe extern "C" fn(source: ALuint) -> ALboolean>;
pub type LPALSOURCEF =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, value: ALfloat)>;
pub type LPALSOURCE3F = ::std::option::Option<
    unsafe extern "C" fn(
        source: ALuint,
        param: ALenum,
        value1: ALfloat,
        value2: ALfloat,
        value3: ALfloat
    )
>;
pub type LPALSOURCEFV = ::std::option::Option<
    unsafe extern "C" fn(source: ALuint, param: ALenum, values: *const ALfloat)
>;
pub type LPALSOURCEI =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, value: ALint)>;
pub type LPALSOURCE3I = ::std::option::Option<
    unsafe extern "C" fn(
        source: ALuint,
        param: ALenum,
        value1: ALint,
        value2: ALint,
        value3: ALint
    )
>;
pub type LPALSOURCEIV = ::std::option::Option<
    unsafe extern "C" fn(source: ALuint, param: ALenum, values: *const ALint)
>;
pub type LPALGETSOURCEF =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, value: *mut ALfloat)>;
pub type LPALGETSOURCE3F = ::std::option::Option<
    unsafe extern "C" fn(
        source: ALuint,
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    )
>;
pub type LPALGETSOURCEFV = ::std::option::Option<
    unsafe extern "C" fn(source: ALuint, param: ALenum, values: *mut ALfloat)
>;
pub type LPALGETSOURCEI =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, value: *mut ALint)>;
pub type LPALGETSOURCE3I = ::std::option::Option<
    unsafe extern "C" fn(
        source: ALuint,
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    )
>;
pub type LPALGETSOURCEIV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, values: *mut ALint)>;
pub type LPALSOURCEPLAYV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALSOURCESTOPV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALSOURCEREWINDV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALSOURCEPAUSEV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALSOURCEPLAY = ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCESTOP = ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCEREWIND = ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCEPAUSE = ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCEQUEUEBUFFERS = ::std::option::Option<
    unsafe extern "C" fn(source: ALuint, nb: ALsizei, buffers: *const ALuint)
>;
pub type LPALSOURCEUNQUEUEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, nb: ALsizei, buffers: *mut ALuint)>;
pub type LPALGENBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, buffers: *mut ALuint)>;
pub type LPALDELETEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, buffers: *const ALuint)>;
pub type LPALISBUFFER = ::std::option::Option<unsafe extern "C" fn(buffer: ALuint) -> ALboolean>;
pub type LPALBUFFERDATA = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        format: ALenum,
        data: *const ALvoid,
        size: ALsizei,
        samplerate: ALsizei
    )
>;
pub type LPALBUFFERF =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, value: ALfloat)>;
pub type LPALBUFFER3F = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        param: ALenum,
        value1: ALfloat,
        value2: ALfloat,
        value3: ALfloat
    )
>;
pub type LPALBUFFERFV = ::std::option::Option<
    unsafe extern "C" fn(buffer: ALuint, param: ALenum, values: *const ALfloat)
>;
pub type LPALBUFFERI =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, value: ALint)>;
pub type LPALBUFFER3I = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        param: ALenum,
        value1: ALint,
        value2: ALint,
        value3: ALint
    )
>;
pub type LPALBUFFERIV = ::std::option::Option<
    unsafe extern "C" fn(buffer: ALuint, param: ALenum, values: *const ALint)
>;
pub type LPALGETBUFFERF =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, value: *mut ALfloat)>;
pub type LPALGETBUFFER3F = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    )
>;
pub type LPALGETBUFFERFV = ::std::option::Option<
    unsafe extern "C" fn(buffer: ALuint, param: ALenum, values: *mut ALfloat)
>;
pub type LPALGETBUFFERI =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, value: *mut ALint)>;
pub type LPALGETBUFFER3I = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    )
>;
pub type LPALGETBUFFERIV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, values: *mut ALint)>;
pub type LPALDOPPLERFACTOR = ::std::option::Option<unsafe extern "C" fn(value: ALfloat)>;
pub type LPALDOPPLERVELOCITY = ::std::option::Option<unsafe extern "C" fn(value: ALfloat)>;
pub type LPALSPEEDOFSOUND = ::std::option::Option<unsafe extern "C" fn(value: ALfloat)>;
pub type LPALDISTANCEMODEL = ::std::option::Option<unsafe extern "C" fn(distanceModel: ALenum)>;
