// automatically generated by rust-bindgen 0.72.0

pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_CXX26: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE: u32 = 1;
pub const _CRT_BUILD_DESKTOP_APP: u32 = 1;
pub const _ARGMAX: u32 = 100;
pub const _CRT_INT_MAX: u32 = 2147483647;
pub const _CRT_FUNCTIONS_REQUIRED: u32 = 1;
pub const _CRT_HAS_CXX17: u32 = 0;
pub const _CRT_HAS_C11: u32 = 1;
pub const _CRT_INTERNAL_NONSTDC_NAMES: u32 = 1;
pub const __STDC_SECURE_LIB__: u32 = 200411;
pub const __GOT_SECURE_LIB__: u32 = 200411;
pub const __STDC_WANT_SECURE_LIB__: u32 = 1;
pub const _SECURECRT_FILL_BUFFER_PATTERN: u32 = 254;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES: u32 = 1;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY: u32 = 0;
pub const FLT_EVAL_METHOD: u32 = 0;
pub const DBL_DECIMAL_DIG: u32 = 17;
pub const DBL_DIG: u32 = 15;
pub const DBL_HAS_SUBNORM: u32 = 1;
pub const DBL_MANT_DIG: u32 = 53;
pub const DBL_MAX_10_EXP: u32 = 308;
pub const DBL_MAX_EXP: u32 = 1024;
pub const DBL_MIN_10_EXP: i32 = -307;
pub const DBL_MIN_EXP: i32 = -1021;
pub const _DBL_RADIX: u32 = 2;
pub const FLT_DECIMAL_DIG: u32 = 9;
pub const FLT_DIG: u32 = 6;
pub const FLT_HAS_SUBNORM: u32 = 1;
pub const FLT_GUARD: u32 = 0;
pub const FLT_MANT_DIG: u32 = 24;
pub const FLT_MAX_10_EXP: u32 = 38;
pub const FLT_MAX_EXP: u32 = 128;
pub const FLT_MIN_10_EXP: i32 = -37;
pub const FLT_MIN_EXP: i32 = -125;
pub const FLT_NORMALIZE: u32 = 0;
pub const FLT_RADIX: u32 = 2;
pub const LDBL_DIG: u32 = 15;
pub const LDBL_HAS_SUBNORM: u32 = 1;
pub const LDBL_MANT_DIG: u32 = 53;
pub const LDBL_MAX_10_EXP: u32 = 308;
pub const LDBL_MAX_EXP: u32 = 1024;
pub const LDBL_MIN_10_EXP: i32 = -307;
pub const LDBL_MIN_EXP: i32 = -1021;
pub const _LDBL_RADIX: u32 = 2;
pub const DECIMAL_DIG: u32 = 17;
pub const _SW_INEXACT: u32 = 1;
pub const _SW_UNDERFLOW: u32 = 2;
pub const _SW_OVERFLOW: u32 = 4;
pub const _SW_ZERODIVIDE: u32 = 8;
pub const _SW_INVALID: u32 = 16;
pub const _SW_DENORMAL: u32 = 524288;
pub const _EM_AMBIGUIOUS: u32 = 2147483648;
pub const _EM_AMBIGUOUS: u32 = 2147483648;
pub const _MCW_EM: u32 = 524319;
pub const _EM_INEXACT: u32 = 1;
pub const _EM_UNDERFLOW: u32 = 2;
pub const _EM_OVERFLOW: u32 = 4;
pub const _EM_ZERODIVIDE: u32 = 8;
pub const _EM_INVALID: u32 = 16;
pub const _EM_DENORMAL: u32 = 524288;
pub const _MCW_RC: u32 = 768;
pub const _RC_NEAR: u32 = 0;
pub const _RC_DOWN: u32 = 256;
pub const _RC_UP: u32 = 512;
pub const _RC_CHOP: u32 = 768;
pub const _MCW_PC: u32 = 196608;
pub const _PC_64: u32 = 0;
pub const _PC_53: u32 = 65536;
pub const _PC_24: u32 = 131072;
pub const _MCW_IC: u32 = 262144;
pub const _IC_AFFINE: u32 = 262144;
pub const _IC_PROJECTIVE: u32 = 0;
pub const _MCW_DN: u32 = 50331648;
pub const _DN_SAVE: u32 = 0;
pub const _DN_FLUSH: u32 = 16777216;
pub const _DN_FLUSH_OPERANDS_SAVE_RESULTS: u32 = 33554432;
pub const _DN_SAVE_OPERANDS_FLUSH_RESULTS: u32 = 50331648;
pub const _SW_UNEMULATED: u32 = 64;
pub const _SW_SQRTNEG: u32 = 128;
pub const _SW_STACKOVERFLOW: u32 = 512;
pub const _SW_STACKUNDERFLOW: u32 = 1024;
pub const _FPE_INVALID: u32 = 129;
pub const _FPE_DENORMAL: u32 = 130;
pub const _FPE_ZERODIVIDE: u32 = 131;
pub const _FPE_OVERFLOW: u32 = 132;
pub const _FPE_UNDERFLOW: u32 = 133;
pub const _FPE_INEXACT: u32 = 134;
pub const _FPE_UNEMULATED: u32 = 135;
pub const _FPE_SQRTNEG: u32 = 136;
pub const _FPE_STACKOVERFLOW: u32 = 138;
pub const _FPE_STACKUNDERFLOW: u32 = 139;
pub const _FPE_EXPLICITGEN: u32 = 140;
pub const _FPE_MULTIPLE_TRAPS: u32 = 141;
pub const _FPE_MULTIPLE_FAULTS: u32 = 142;
pub const _FPCLASS_SNAN: u32 = 1;
pub const _FPCLASS_QNAN: u32 = 2;
pub const _FPCLASS_NINF: u32 = 4;
pub const _FPCLASS_NN: u32 = 8;
pub const _FPCLASS_ND: u32 = 16;
pub const _FPCLASS_NZ: u32 = 32;
pub const _FPCLASS_PZ: u32 = 64;
pub const _FPCLASS_PD: u32 = 128;
pub const _FPCLASS_PN: u32 = 256;
pub const _FPCLASS_PINF: u32 = 512;
pub const _CW_DEFAULT: u32 = 524319;
pub const DBL_RADIX: u32 = 2;
pub const LDBL_RADIX: u32 = 2;
pub const EM_AMBIGUIOUS: u32 = 2147483648;
pub const EM_AMBIGUOUS: u32 = 2147483648;
pub const MCW_EM: u32 = 524319;
pub const EM_INVALID: u32 = 16;
pub const EM_DENORMAL: u32 = 524288;
pub const EM_ZERODIVIDE: u32 = 8;
pub const EM_OVERFLOW: u32 = 4;
pub const EM_UNDERFLOW: u32 = 2;
pub const EM_INEXACT: u32 = 1;
pub const MCW_IC: u32 = 262144;
pub const IC_AFFINE: u32 = 262144;
pub const IC_PROJECTIVE: u32 = 0;
pub const MCW_RC: u32 = 768;
pub const RC_CHOP: u32 = 768;
pub const RC_UP: u32 = 512;
pub const RC_DOWN: u32 = 256;
pub const RC_NEAR: u32 = 0;
pub const MCW_PC: u32 = 196608;
pub const PC_24: u32 = 131072;
pub const PC_53: u32 = 65536;
pub const PC_64: u32 = 0;
pub const CW_DEFAULT: u32 = 524319;
pub const SW_INVALID: u32 = 16;
pub const SW_DENORMAL: u32 = 524288;
pub const SW_ZERODIVIDE: u32 = 8;
pub const SW_OVERFLOW: u32 = 4;
pub const SW_UNDERFLOW: u32 = 2;
pub const SW_INEXACT: u32 = 1;
pub const SW_UNEMULATED: u32 = 64;
pub const SW_SQRTNEG: u32 = 128;
pub const SW_STACKOVERFLOW: u32 = 512;
pub const SW_STACKUNDERFLOW: u32 = 1024;
pub const FPE_INVALID: u32 = 129;
pub const FPE_DENORMAL: u32 = 130;
pub const FPE_ZERODIVIDE: u32 = 131;
pub const FPE_OVERFLOW: u32 = 132;
pub const FPE_UNDERFLOW: u32 = 133;
pub const FPE_INEXACT: u32 = 134;
pub const FPE_UNEMULATED: u32 = 135;
pub const FPE_SQRTNEG: u32 = 136;
pub const FPE_STACKOVERFLOW: u32 = 138;
pub const FPE_STACKUNDERFLOW: u32 = 139;
pub const FPE_EXPLICITGEN: u32 = 140;
pub const ALC_INVALID: u32 = 0;
pub const ALC_VERSION_0_1: u32 = 1;
pub const ALC_FALSE: u32 = 0;
pub const ALC_TRUE: u32 = 1;
pub const ALC_FREQUENCY: u32 = 4103;
pub const ALC_REFRESH: u32 = 4104;
pub const ALC_SYNC: u32 = 4105;
pub const ALC_MONO_SOURCES: u32 = 4112;
pub const ALC_STEREO_SOURCES: u32 = 4113;
pub const ALC_NO_ERROR: u32 = 0;
pub const ALC_INVALID_DEVICE: u32 = 40961;
pub const ALC_INVALID_CONTEXT: u32 = 40962;
pub const ALC_INVALID_ENUM: u32 = 40963;
pub const ALC_INVALID_VALUE: u32 = 40964;
pub const ALC_OUT_OF_MEMORY: u32 = 40965;
pub const ALC_MAJOR_VERSION: u32 = 4096;
pub const ALC_MINOR_VERSION: u32 = 4097;
pub const ALC_ATTRIBUTES_SIZE: u32 = 4098;
pub const ALC_ALL_ATTRIBUTES: u32 = 4099;
pub const ALC_DEFAULT_DEVICE_SPECIFIER: u32 = 4100;
pub const ALC_DEVICE_SPECIFIER: u32 = 4101;
pub const ALC_EXTENSIONS: u32 = 4102;
pub const ALC_EXT_CAPTURE: u32 = 1;
pub const ALC_CAPTURE_DEVICE_SPECIFIER: u32 = 784;
pub const ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER: u32 = 785;
pub const ALC_CAPTURE_SAMPLES: u32 = 786;
pub const ALC_ENUMERATE_ALL_EXT: u32 = 1;
pub const ALC_DEFAULT_ALL_DEVICES_SPECIFIER: u32 = 4114;
pub const ALC_ALL_DEVICES_SPECIFIER: u32 = 4115;
pub const AL_INVALID: i32 = -1;
pub const AL_NONE: u32 = 0;
pub const AL_FALSE: u32 = 0;
pub const AL_TRUE: u32 = 1;
pub const AL_SOURCE_RELATIVE: u32 = 514;
pub const AL_CONE_INNER_ANGLE: u32 = 4097;
pub const AL_CONE_OUTER_ANGLE: u32 = 4098;
pub const AL_PITCH: u32 = 4099;
pub const AL_POSITION: u32 = 4100;
pub const AL_DIRECTION: u32 = 4101;
pub const AL_VELOCITY: u32 = 4102;
pub const AL_LOOPING: u32 = 4103;
pub const AL_BUFFER: u32 = 4105;
pub const AL_GAIN: u32 = 4106;
pub const AL_MIN_GAIN: u32 = 4109;
pub const AL_MAX_GAIN: u32 = 4110;
pub const AL_ORIENTATION: u32 = 4111;
pub const AL_SOURCE_STATE: u32 = 4112;
pub const AL_INITIAL: u32 = 4113;
pub const AL_PLAYING: u32 = 4114;
pub const AL_PAUSED: u32 = 4115;
pub const AL_STOPPED: u32 = 4116;
pub const AL_BUFFERS_QUEUED: u32 = 4117;
pub const AL_BUFFERS_PROCESSED: u32 = 4118;
pub const AL_REFERENCE_DISTANCE: u32 = 4128;
pub const AL_ROLLOFF_FACTOR: u32 = 4129;
pub const AL_CONE_OUTER_GAIN: u32 = 4130;
pub const AL_MAX_DISTANCE: u32 = 4131;
pub const AL_SEC_OFFSET: u32 = 4132;
pub const AL_SAMPLE_OFFSET: u32 = 4133;
pub const AL_BYTE_OFFSET: u32 = 4134;
pub const AL_SOURCE_TYPE: u32 = 4135;
pub const AL_STATIC: u32 = 4136;
pub const AL_STREAMING: u32 = 4137;
pub const AL_UNDETERMINED: u32 = 4144;
pub const AL_FORMAT_MONO8: u32 = 4352;
pub const AL_FORMAT_MONO16: u32 = 4353;
pub const AL_FORMAT_STEREO8: u32 = 4354;
pub const AL_FORMAT_STEREO16: u32 = 4355;
pub const AL_FREQUENCY: u32 = 8193;
pub const AL_BITS: u32 = 8194;
pub const AL_CHANNELS: u32 = 8195;
pub const AL_SIZE: u32 = 8196;
pub const AL_UNUSED: u32 = 8208;
pub const AL_PENDING: u32 = 8209;
pub const AL_PROCESSED: u32 = 8210;
pub const AL_NO_ERROR: u32 = 0;
pub const AL_INVALID_NAME: u32 = 40961;
pub const AL_INVALID_ENUM: u32 = 40962;
pub const AL_INVALID_VALUE: u32 = 40963;
pub const AL_INVALID_OPERATION: u32 = 40964;
pub const AL_OUT_OF_MEMORY: u32 = 40965;
pub const AL_VENDOR: u32 = 45057;
pub const AL_VERSION: u32 = 45058;
pub const AL_RENDERER: u32 = 45059;
pub const AL_EXTENSIONS: u32 = 45060;
pub const AL_DOPPLER_FACTOR: u32 = 49152;
pub const AL_DOPPLER_VELOCITY: u32 = 49153;
pub const AL_SPEED_OF_SOUND: u32 = 49155;
pub const AL_DISTANCE_MODEL: u32 = 53248;
pub const AL_INVERSE_DISTANCE: u32 = 53249;
pub const AL_INVERSE_DISTANCE_CLAMPED: u32 = 53250;
pub const AL_LINEAR_DISTANCE: u32 = 53251;
pub const AL_LINEAR_DISTANCE_CLAMPED: u32 = 53252;
pub const AL_EXPONENT_DISTANCE: u32 = 53253;
pub const AL_EXPONENT_DISTANCE_CLAMPED: u32 = 53254;
pub const ALC_EXT_EFX_NAME: &[u8; 12] = b"ALC_EXT_EFX\0";
pub const ALC_EFX_MAJOR_VERSION: u32 = 131073;
pub const ALC_EFX_MINOR_VERSION: u32 = 131074;
pub const ALC_MAX_AUXILIARY_SENDS: u32 = 131075;
pub const AL_METERS_PER_UNIT: u32 = 131076;
pub const AL_DIRECT_FILTER: u32 = 131077;
pub const AL_AUXILIARY_SEND_FILTER: u32 = 131078;
pub const AL_AIR_ABSORPTION_FACTOR: u32 = 131079;
pub const AL_ROOM_ROLLOFF_FACTOR: u32 = 131080;
pub const AL_CONE_OUTER_GAINHF: u32 = 131081;
pub const AL_DIRECT_FILTER_GAINHF_AUTO: u32 = 131082;
pub const AL_AUXILIARY_SEND_FILTER_GAIN_AUTO: u32 = 131083;
pub const AL_AUXILIARY_SEND_FILTER_GAINHF_AUTO: u32 = 131084;
pub const AL_REVERB_DENSITY: u32 = 1;
pub const AL_REVERB_DIFFUSION: u32 = 2;
pub const AL_REVERB_GAIN: u32 = 3;
pub const AL_REVERB_GAINHF: u32 = 4;
pub const AL_REVERB_DECAY_TIME: u32 = 5;
pub const AL_REVERB_DECAY_HFRATIO: u32 = 6;
pub const AL_REVERB_REFLECTIONS_GAIN: u32 = 7;
pub const AL_REVERB_REFLECTIONS_DELAY: u32 = 8;
pub const AL_REVERB_LATE_REVERB_GAIN: u32 = 9;
pub const AL_REVERB_LATE_REVERB_DELAY: u32 = 10;
pub const AL_REVERB_AIR_ABSORPTION_GAINHF: u32 = 11;
pub const AL_REVERB_ROOM_ROLLOFF_FACTOR: u32 = 12;
pub const AL_REVERB_DECAY_HFLIMIT: u32 = 13;
pub const AL_EAXREVERB_DENSITY: u32 = 1;
pub const AL_EAXREVERB_DIFFUSION: u32 = 2;
pub const AL_EAXREVERB_GAIN: u32 = 3;
pub const AL_EAXREVERB_GAINHF: u32 = 4;
pub const AL_EAXREVERB_GAINLF: u32 = 5;
pub const AL_EAXREVERB_DECAY_TIME: u32 = 6;
pub const AL_EAXREVERB_DECAY_HFRATIO: u32 = 7;
pub const AL_EAXREVERB_DECAY_LFRATIO: u32 = 8;
pub const AL_EAXREVERB_REFLECTIONS_GAIN: u32 = 9;
pub const AL_EAXREVERB_REFLECTIONS_DELAY: u32 = 10;
pub const AL_EAXREVERB_REFLECTIONS_PAN: u32 = 11;
pub const AL_EAXREVERB_LATE_REVERB_GAIN: u32 = 12;
pub const AL_EAXREVERB_LATE_REVERB_DELAY: u32 = 13;
pub const AL_EAXREVERB_LATE_REVERB_PAN: u32 = 14;
pub const AL_EAXREVERB_ECHO_TIME: u32 = 15;
pub const AL_EAXREVERB_ECHO_DEPTH: u32 = 16;
pub const AL_EAXREVERB_MODULATION_TIME: u32 = 17;
pub const AL_EAXREVERB_MODULATION_DEPTH: u32 = 18;
pub const AL_EAXREVERB_AIR_ABSORPTION_GAINHF: u32 = 19;
pub const AL_EAXREVERB_HFREFERENCE: u32 = 20;
pub const AL_EAXREVERB_LFREFERENCE: u32 = 21;
pub const AL_EAXREVERB_ROOM_ROLLOFF_FACTOR: u32 = 22;
pub const AL_EAXREVERB_DECAY_HFLIMIT: u32 = 23;
pub const AL_CHORUS_WAVEFORM: u32 = 1;
pub const AL_CHORUS_PHASE: u32 = 2;
pub const AL_CHORUS_RATE: u32 = 3;
pub const AL_CHORUS_DEPTH: u32 = 4;
pub const AL_CHORUS_FEEDBACK: u32 = 5;
pub const AL_CHORUS_DELAY: u32 = 6;
pub const AL_DISTORTION_EDGE: u32 = 1;
pub const AL_DISTORTION_GAIN: u32 = 2;
pub const AL_DISTORTION_LOWPASS_CUTOFF: u32 = 3;
pub const AL_DISTORTION_EQCENTER: u32 = 4;
pub const AL_DISTORTION_EQBANDWIDTH: u32 = 5;
pub const AL_ECHO_DELAY: u32 = 1;
pub const AL_ECHO_LRDELAY: u32 = 2;
pub const AL_ECHO_DAMPING: u32 = 3;
pub const AL_ECHO_FEEDBACK: u32 = 4;
pub const AL_ECHO_SPREAD: u32 = 5;
pub const AL_FLANGER_WAVEFORM: u32 = 1;
pub const AL_FLANGER_PHASE: u32 = 2;
pub const AL_FLANGER_RATE: u32 = 3;
pub const AL_FLANGER_DEPTH: u32 = 4;
pub const AL_FLANGER_FEEDBACK: u32 = 5;
pub const AL_FLANGER_DELAY: u32 = 6;
pub const AL_FREQUENCY_SHIFTER_FREQUENCY: u32 = 1;
pub const AL_FREQUENCY_SHIFTER_LEFT_DIRECTION: u32 = 2;
pub const AL_FREQUENCY_SHIFTER_RIGHT_DIRECTION: u32 = 3;
pub const AL_VOCAL_MORPHER_PHONEMEA: u32 = 1;
pub const AL_VOCAL_MORPHER_PHONEMEA_COARSE_TUNING: u32 = 2;
pub const AL_VOCAL_MORPHER_PHONEMEB: u32 = 3;
pub const AL_VOCAL_MORPHER_PHONEMEB_COARSE_TUNING: u32 = 4;
pub const AL_VOCAL_MORPHER_WAVEFORM: u32 = 5;
pub const AL_VOCAL_MORPHER_RATE: u32 = 6;
pub const AL_PITCH_SHIFTER_COARSE_TUNE: u32 = 1;
pub const AL_PITCH_SHIFTER_FINE_TUNE: u32 = 2;
pub const AL_RING_MODULATOR_FREQUENCY: u32 = 1;
pub const AL_RING_MODULATOR_HIGHPASS_CUTOFF: u32 = 2;
pub const AL_RING_MODULATOR_WAVEFORM: u32 = 3;
pub const AL_AUTOWAH_ATTACK_TIME: u32 = 1;
pub const AL_AUTOWAH_RELEASE_TIME: u32 = 2;
pub const AL_AUTOWAH_RESONANCE: u32 = 3;
pub const AL_AUTOWAH_PEAK_GAIN: u32 = 4;
pub const AL_COMPRESSOR_ONOFF: u32 = 1;
pub const AL_EQUALIZER_LOW_GAIN: u32 = 1;
pub const AL_EQUALIZER_LOW_CUTOFF: u32 = 2;
pub const AL_EQUALIZER_MID1_GAIN: u32 = 3;
pub const AL_EQUALIZER_MID1_CENTER: u32 = 4;
pub const AL_EQUALIZER_MID1_WIDTH: u32 = 5;
pub const AL_EQUALIZER_MID2_GAIN: u32 = 6;
pub const AL_EQUALIZER_MID2_CENTER: u32 = 7;
pub const AL_EQUALIZER_MID2_WIDTH: u32 = 8;
pub const AL_EQUALIZER_HIGH_GAIN: u32 = 9;
pub const AL_EQUALIZER_HIGH_CUTOFF: u32 = 10;
pub const AL_EFFECT_FIRST_PARAMETER: u32 = 0;
pub const AL_EFFECT_LAST_PARAMETER: u32 = 32768;
pub const AL_EFFECT_TYPE: u32 = 32769;
pub const AL_EFFECT_NULL: u32 = 0;
pub const AL_EFFECT_REVERB: u32 = 1;
pub const AL_EFFECT_CHORUS: u32 = 2;
pub const AL_EFFECT_DISTORTION: u32 = 3;
pub const AL_EFFECT_ECHO: u32 = 4;
pub const AL_EFFECT_FLANGER: u32 = 5;
pub const AL_EFFECT_FREQUENCY_SHIFTER: u32 = 6;
pub const AL_EFFECT_VOCAL_MORPHER: u32 = 7;
pub const AL_EFFECT_PITCH_SHIFTER: u32 = 8;
pub const AL_EFFECT_RING_MODULATOR: u32 = 9;
pub const AL_EFFECT_AUTOWAH: u32 = 10;
pub const AL_EFFECT_COMPRESSOR: u32 = 11;
pub const AL_EFFECT_EQUALIZER: u32 = 12;
pub const AL_EFFECT_EAXREVERB: u32 = 32768;
pub const AL_EFFECTSLOT_EFFECT: u32 = 1;
pub const AL_EFFECTSLOT_GAIN: u32 = 2;
pub const AL_EFFECTSLOT_AUXILIARY_SEND_AUTO: u32 = 3;
pub const AL_EFFECTSLOT_NULL: u32 = 0;
pub const AL_LOWPASS_GAIN: u32 = 1;
pub const AL_LOWPASS_GAINHF: u32 = 2;
pub const AL_HIGHPASS_GAIN: u32 = 1;
pub const AL_HIGHPASS_GAINLF: u32 = 2;
pub const AL_BANDPASS_GAIN: u32 = 1;
pub const AL_BANDPASS_GAINLF: u32 = 2;
pub const AL_BANDPASS_GAINHF: u32 = 3;
pub const AL_FILTER_FIRST_PARAMETER: u32 = 0;
pub const AL_FILTER_LAST_PARAMETER: u32 = 32768;
pub const AL_FILTER_TYPE: u32 = 32769;
pub const AL_FILTER_NULL: u32 = 0;
pub const AL_FILTER_LOWPASS: u32 = 1;
pub const AL_FILTER_HIGHPASS: u32 = 2;
pub const AL_FILTER_BANDPASS: u32 = 3;
pub const AL_LOWPASS_MIN_GAIN: f64 = 0.0;
pub const AL_LOWPASS_MAX_GAIN: f64 = 1.0;
pub const AL_LOWPASS_DEFAULT_GAIN: f64 = 1.0;
pub const AL_LOWPASS_MIN_GAINHF: f64 = 0.0;
pub const AL_LOWPASS_MAX_GAINHF: f64 = 1.0;
pub const AL_LOWPASS_DEFAULT_GAINHF: f64 = 1.0;
pub const AL_HIGHPASS_MIN_GAIN: f64 = 0.0;
pub const AL_HIGHPASS_MAX_GAIN: f64 = 1.0;
pub const AL_HIGHPASS_DEFAULT_GAIN: f64 = 1.0;
pub const AL_HIGHPASS_MIN_GAINLF: f64 = 0.0;
pub const AL_HIGHPASS_MAX_GAINLF: f64 = 1.0;
pub const AL_HIGHPASS_DEFAULT_GAINLF: f64 = 1.0;
pub const AL_BANDPASS_MIN_GAIN: f64 = 0.0;
pub const AL_BANDPASS_MAX_GAIN: f64 = 1.0;
pub const AL_BANDPASS_DEFAULT_GAIN: f64 = 1.0;
pub const AL_BANDPASS_MIN_GAINHF: f64 = 0.0;
pub const AL_BANDPASS_MAX_GAINHF: f64 = 1.0;
pub const AL_BANDPASS_DEFAULT_GAINHF: f64 = 1.0;
pub const AL_BANDPASS_MIN_GAINLF: f64 = 0.0;
pub const AL_BANDPASS_MAX_GAINLF: f64 = 1.0;
pub const AL_BANDPASS_DEFAULT_GAINLF: f64 = 1.0;
pub const AL_REVERB_MIN_DENSITY: f64 = 0.0;
pub const AL_REVERB_MAX_DENSITY: f64 = 1.0;
pub const AL_REVERB_DEFAULT_DENSITY: f64 = 1.0;
pub const AL_REVERB_MIN_DIFFUSION: f64 = 0.0;
pub const AL_REVERB_MAX_DIFFUSION: f64 = 1.0;
pub const AL_REVERB_DEFAULT_DIFFUSION: f64 = 1.0;
pub const AL_REVERB_MIN_GAIN: f64 = 0.0;
pub const AL_REVERB_MAX_GAIN: f64 = 1.0;
pub const AL_REVERB_DEFAULT_GAIN: f64 = 0.32;
pub const AL_REVERB_MIN_GAINHF: f64 = 0.0;
pub const AL_REVERB_MAX_GAINHF: f64 = 1.0;
pub const AL_REVERB_DEFAULT_GAINHF: f64 = 0.89;
pub const AL_REVERB_MIN_DECAY_TIME: f64 = 0.1;
pub const AL_REVERB_MAX_DECAY_TIME: f64 = 20.0;
pub const AL_REVERB_DEFAULT_DECAY_TIME: f64 = 1.49;
pub const AL_REVERB_MIN_DECAY_HFRATIO: f64 = 0.1;
pub const AL_REVERB_MAX_DECAY_HFRATIO: f64 = 2.0;
pub const AL_REVERB_DEFAULT_DECAY_HFRATIO: f64 = 0.83;
pub const AL_REVERB_MIN_REFLECTIONS_GAIN: f64 = 0.0;
pub const AL_REVERB_MAX_REFLECTIONS_GAIN: f64 = 3.16;
pub const AL_REVERB_DEFAULT_REFLECTIONS_GAIN: f64 = 0.05;
pub const AL_REVERB_MIN_REFLECTIONS_DELAY: f64 = 0.0;
pub const AL_REVERB_MAX_REFLECTIONS_DELAY: f64 = 0.3;
pub const AL_REVERB_DEFAULT_REFLECTIONS_DELAY: f64 = 0.007;
pub const AL_REVERB_MIN_LATE_REVERB_GAIN: f64 = 0.0;
pub const AL_REVERB_MAX_LATE_REVERB_GAIN: f64 = 10.0;
pub const AL_REVERB_DEFAULT_LATE_REVERB_GAIN: f64 = 1.26;
pub const AL_REVERB_MIN_LATE_REVERB_DELAY: f64 = 0.0;
pub const AL_REVERB_MAX_LATE_REVERB_DELAY: f64 = 0.1;
pub const AL_REVERB_DEFAULT_LATE_REVERB_DELAY: f64 = 0.011;
pub const AL_REVERB_MIN_AIR_ABSORPTION_GAINHF: f64 = 0.892;
pub const AL_REVERB_MAX_AIR_ABSORPTION_GAINHF: f64 = 1.0;
pub const AL_REVERB_DEFAULT_AIR_ABSORPTION_GAINHF: f64 = 0.994;
pub const AL_REVERB_MIN_ROOM_ROLLOFF_FACTOR: f64 = 0.0;
pub const AL_REVERB_MAX_ROOM_ROLLOFF_FACTOR: f64 = 10.0;
pub const AL_REVERB_DEFAULT_ROOM_ROLLOFF_FACTOR: f64 = 0.0;
pub const AL_REVERB_MIN_DECAY_HFLIMIT: u32 = 0;
pub const AL_REVERB_MAX_DECAY_HFLIMIT: u32 = 1;
pub const AL_REVERB_DEFAULT_DECAY_HFLIMIT: u32 = 1;
pub const AL_EAXREVERB_MIN_DENSITY: f64 = 0.0;
pub const AL_EAXREVERB_MAX_DENSITY: f64 = 1.0;
pub const AL_EAXREVERB_DEFAULT_DENSITY: f64 = 1.0;
pub const AL_EAXREVERB_MIN_DIFFUSION: f64 = 0.0;
pub const AL_EAXREVERB_MAX_DIFFUSION: f64 = 1.0;
pub const AL_EAXREVERB_DEFAULT_DIFFUSION: f64 = 1.0;
pub const AL_EAXREVERB_MIN_GAIN: f64 = 0.0;
pub const AL_EAXREVERB_MAX_GAIN: f64 = 1.0;
pub const AL_EAXREVERB_DEFAULT_GAIN: f64 = 0.32;
pub const AL_EAXREVERB_MIN_GAINHF: f64 = 0.0;
pub const AL_EAXREVERB_MAX_GAINHF: f64 = 1.0;
pub const AL_EAXREVERB_DEFAULT_GAINHF: f64 = 0.89;
pub const AL_EAXREVERB_MIN_GAINLF: f64 = 0.0;
pub const AL_EAXREVERB_MAX_GAINLF: f64 = 1.0;
pub const AL_EAXREVERB_DEFAULT_GAINLF: f64 = 1.0;
pub const AL_EAXREVERB_MIN_DECAY_TIME: f64 = 0.1;
pub const AL_EAXREVERB_MAX_DECAY_TIME: f64 = 20.0;
pub const AL_EAXREVERB_DEFAULT_DECAY_TIME: f64 = 1.49;
pub const AL_EAXREVERB_MIN_DECAY_HFRATIO: f64 = 0.1;
pub const AL_EAXREVERB_MAX_DECAY_HFRATIO: f64 = 2.0;
pub const AL_EAXREVERB_DEFAULT_DECAY_HFRATIO: f64 = 0.83;
pub const AL_EAXREVERB_MIN_DECAY_LFRATIO: f64 = 0.1;
pub const AL_EAXREVERB_MAX_DECAY_LFRATIO: f64 = 2.0;
pub const AL_EAXREVERB_DEFAULT_DECAY_LFRATIO: f64 = 1.0;
pub const AL_EAXREVERB_MIN_REFLECTIONS_GAIN: f64 = 0.0;
pub const AL_EAXREVERB_MAX_REFLECTIONS_GAIN: f64 = 3.16;
pub const AL_EAXREVERB_DEFAULT_REFLECTIONS_GAIN: f64 = 0.05;
pub const AL_EAXREVERB_MIN_REFLECTIONS_DELAY: f64 = 0.0;
pub const AL_EAXREVERB_MAX_REFLECTIONS_DELAY: f64 = 0.3;
pub const AL_EAXREVERB_DEFAULT_REFLECTIONS_DELAY: f64 = 0.007;
pub const AL_EAXREVERB_DEFAULT_REFLECTIONS_PAN_XYZ: f64 = 0.0;
pub const AL_EAXREVERB_MIN_LATE_REVERB_GAIN: f64 = 0.0;
pub const AL_EAXREVERB_MAX_LATE_REVERB_GAIN: f64 = 10.0;
pub const AL_EAXREVERB_DEFAULT_LATE_REVERB_GAIN: f64 = 1.26;
pub const AL_EAXREVERB_MIN_LATE_REVERB_DELAY: f64 = 0.0;
pub const AL_EAXREVERB_MAX_LATE_REVERB_DELAY: f64 = 0.1;
pub const AL_EAXREVERB_DEFAULT_LATE_REVERB_DELAY: f64 = 0.011;
pub const AL_EAXREVERB_DEFAULT_LATE_REVERB_PAN_XYZ: f64 = 0.0;
pub const AL_EAXREVERB_MIN_ECHO_TIME: f64 = 0.075;
pub const AL_EAXREVERB_MAX_ECHO_TIME: f64 = 0.25;
pub const AL_EAXREVERB_DEFAULT_ECHO_TIME: f64 = 0.25;
pub const AL_EAXREVERB_MIN_ECHO_DEPTH: f64 = 0.0;
pub const AL_EAXREVERB_MAX_ECHO_DEPTH: f64 = 1.0;
pub const AL_EAXREVERB_DEFAULT_ECHO_DEPTH: f64 = 0.0;
pub const AL_EAXREVERB_MIN_MODULATION_TIME: f64 = 0.04;
pub const AL_EAXREVERB_MAX_MODULATION_TIME: f64 = 4.0;
pub const AL_EAXREVERB_DEFAULT_MODULATION_TIME: f64 = 0.25;
pub const AL_EAXREVERB_MIN_MODULATION_DEPTH: f64 = 0.0;
pub const AL_EAXREVERB_MAX_MODULATION_DEPTH: f64 = 1.0;
pub const AL_EAXREVERB_DEFAULT_MODULATION_DEPTH: f64 = 0.0;
pub const AL_EAXREVERB_MIN_AIR_ABSORPTION_GAINHF: f64 = 0.892;
pub const AL_EAXREVERB_MAX_AIR_ABSORPTION_GAINHF: f64 = 1.0;
pub const AL_EAXREVERB_DEFAULT_AIR_ABSORPTION_GAINHF: f64 = 0.994;
pub const AL_EAXREVERB_MIN_HFREFERENCE: f64 = 1000.0;
pub const AL_EAXREVERB_MAX_HFREFERENCE: f64 = 20000.0;
pub const AL_EAXREVERB_DEFAULT_HFREFERENCE: f64 = 5000.0;
pub const AL_EAXREVERB_MIN_LFREFERENCE: f64 = 20.0;
pub const AL_EAXREVERB_MAX_LFREFERENCE: f64 = 1000.0;
pub const AL_EAXREVERB_DEFAULT_LFREFERENCE: f64 = 250.0;
pub const AL_EAXREVERB_MIN_ROOM_ROLLOFF_FACTOR: f64 = 0.0;
pub const AL_EAXREVERB_MAX_ROOM_ROLLOFF_FACTOR: f64 = 10.0;
pub const AL_EAXREVERB_DEFAULT_ROOM_ROLLOFF_FACTOR: f64 = 0.0;
pub const AL_EAXREVERB_MIN_DECAY_HFLIMIT: u32 = 0;
pub const AL_EAXREVERB_MAX_DECAY_HFLIMIT: u32 = 1;
pub const AL_EAXREVERB_DEFAULT_DECAY_HFLIMIT: u32 = 1;
pub const AL_CHORUS_WAVEFORM_SINUSOID: u32 = 0;
pub const AL_CHORUS_WAVEFORM_TRIANGLE: u32 = 1;
pub const AL_CHORUS_MIN_WAVEFORM: u32 = 0;
pub const AL_CHORUS_MAX_WAVEFORM: u32 = 1;
pub const AL_CHORUS_DEFAULT_WAVEFORM: u32 = 1;
pub const AL_CHORUS_MIN_PHASE: i32 = -180;
pub const AL_CHORUS_MAX_PHASE: u32 = 180;
pub const AL_CHORUS_DEFAULT_PHASE: u32 = 90;
pub const AL_CHORUS_MIN_RATE: f64 = 0.0;
pub const AL_CHORUS_MAX_RATE: f64 = 10.0;
pub const AL_CHORUS_DEFAULT_RATE: f64 = 1.1;
pub const AL_CHORUS_MIN_DEPTH: f64 = 0.0;
pub const AL_CHORUS_MAX_DEPTH: f64 = 1.0;
pub const AL_CHORUS_DEFAULT_DEPTH: f64 = 0.1;
pub const AL_CHORUS_MIN_FEEDBACK: f64 = -1.0;
pub const AL_CHORUS_MAX_FEEDBACK: f64 = 1.0;
pub const AL_CHORUS_DEFAULT_FEEDBACK: f64 = 0.25;
pub const AL_CHORUS_MIN_DELAY: f64 = 0.0;
pub const AL_CHORUS_MAX_DELAY: f64 = 0.016;
pub const AL_CHORUS_DEFAULT_DELAY: f64 = 0.016;
pub const AL_DISTORTION_MIN_EDGE: f64 = 0.0;
pub const AL_DISTORTION_MAX_EDGE: f64 = 1.0;
pub const AL_DISTORTION_DEFAULT_EDGE: f64 = 0.2;
pub const AL_DISTORTION_MIN_GAIN: f64 = 0.01;
pub const AL_DISTORTION_MAX_GAIN: f64 = 1.0;
pub const AL_DISTORTION_DEFAULT_GAIN: f64 = 0.05;
pub const AL_DISTORTION_MIN_LOWPASS_CUTOFF: f64 = 80.0;
pub const AL_DISTORTION_MAX_LOWPASS_CUTOFF: f64 = 24000.0;
pub const AL_DISTORTION_DEFAULT_LOWPASS_CUTOFF: f64 = 8000.0;
pub const AL_DISTORTION_MIN_EQCENTER: f64 = 80.0;
pub const AL_DISTORTION_MAX_EQCENTER: f64 = 24000.0;
pub const AL_DISTORTION_DEFAULT_EQCENTER: f64 = 3600.0;
pub const AL_DISTORTION_MIN_EQBANDWIDTH: f64 = 80.0;
pub const AL_DISTORTION_MAX_EQBANDWIDTH: f64 = 24000.0;
pub const AL_DISTORTION_DEFAULT_EQBANDWIDTH: f64 = 3600.0;
pub const AL_ECHO_MIN_DELAY: f64 = 0.0;
pub const AL_ECHO_MAX_DELAY: f64 = 0.207;
pub const AL_ECHO_DEFAULT_DELAY: f64 = 0.1;
pub const AL_ECHO_MIN_LRDELAY: f64 = 0.0;
pub const AL_ECHO_MAX_LRDELAY: f64 = 0.404;
pub const AL_ECHO_DEFAULT_LRDELAY: f64 = 0.1;
pub const AL_ECHO_MIN_DAMPING: f64 = 0.0;
pub const AL_ECHO_MAX_DAMPING: f64 = 0.99;
pub const AL_ECHO_DEFAULT_DAMPING: f64 = 0.5;
pub const AL_ECHO_MIN_FEEDBACK: f64 = 0.0;
pub const AL_ECHO_MAX_FEEDBACK: f64 = 1.0;
pub const AL_ECHO_DEFAULT_FEEDBACK: f64 = 0.5;
pub const AL_ECHO_MIN_SPREAD: f64 = -1.0;
pub const AL_ECHO_MAX_SPREAD: f64 = 1.0;
pub const AL_ECHO_DEFAULT_SPREAD: f64 = -1.0;
pub const AL_FLANGER_WAVEFORM_SINUSOID: u32 = 0;
pub const AL_FLANGER_WAVEFORM_TRIANGLE: u32 = 1;
pub const AL_FLANGER_MIN_WAVEFORM: u32 = 0;
pub const AL_FLANGER_MAX_WAVEFORM: u32 = 1;
pub const AL_FLANGER_DEFAULT_WAVEFORM: u32 = 1;
pub const AL_FLANGER_MIN_PHASE: i32 = -180;
pub const AL_FLANGER_MAX_PHASE: u32 = 180;
pub const AL_FLANGER_DEFAULT_PHASE: u32 = 0;
pub const AL_FLANGER_MIN_RATE: f64 = 0.0;
pub const AL_FLANGER_MAX_RATE: f64 = 10.0;
pub const AL_FLANGER_DEFAULT_RATE: f64 = 0.27;
pub const AL_FLANGER_MIN_DEPTH: f64 = 0.0;
pub const AL_FLANGER_MAX_DEPTH: f64 = 1.0;
pub const AL_FLANGER_DEFAULT_DEPTH: f64 = 1.0;
pub const AL_FLANGER_MIN_FEEDBACK: f64 = -1.0;
pub const AL_FLANGER_MAX_FEEDBACK: f64 = 1.0;
pub const AL_FLANGER_DEFAULT_FEEDBACK: f64 = -0.5;
pub const AL_FLANGER_MIN_DELAY: f64 = 0.0;
pub const AL_FLANGER_MAX_DELAY: f64 = 0.004;
pub const AL_FLANGER_DEFAULT_DELAY: f64 = 0.002;
pub const AL_FREQUENCY_SHIFTER_MIN_FREQUENCY: f64 = 0.0;
pub const AL_FREQUENCY_SHIFTER_MAX_FREQUENCY: f64 = 24000.0;
pub const AL_FREQUENCY_SHIFTER_DEFAULT_FREQUENCY: f64 = 0.0;
pub const AL_FREQUENCY_SHIFTER_MIN_LEFT_DIRECTION: u32 = 0;
pub const AL_FREQUENCY_SHIFTER_MAX_LEFT_DIRECTION: u32 = 2;
pub const AL_FREQUENCY_SHIFTER_DEFAULT_LEFT_DIRECTION: u32 = 0;
pub const AL_FREQUENCY_SHIFTER_DIRECTION_DOWN: u32 = 0;
pub const AL_FREQUENCY_SHIFTER_DIRECTION_UP: u32 = 1;
pub const AL_FREQUENCY_SHIFTER_DIRECTION_OFF: u32 = 2;
pub const AL_FREQUENCY_SHIFTER_MIN_RIGHT_DIRECTION: u32 = 0;
pub const AL_FREQUENCY_SHIFTER_MAX_RIGHT_DIRECTION: u32 = 2;
pub const AL_FREQUENCY_SHIFTER_DEFAULT_RIGHT_DIRECTION: u32 = 0;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEA: u32 = 0;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEA: u32 = 29;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEA: u32 = 0;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEA_COARSE_TUNING: i32 = -24;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEA_COARSE_TUNING: u32 = 24;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEA_COARSE_TUNING: u32 = 0;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEB: u32 = 0;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEB: u32 = 29;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEB: u32 = 10;
pub const AL_VOCAL_MORPHER_MIN_PHONEMEB_COARSE_TUNING: i32 = -24;
pub const AL_VOCAL_MORPHER_MAX_PHONEMEB_COARSE_TUNING: u32 = 24;
pub const AL_VOCAL_MORPHER_DEFAULT_PHONEMEB_COARSE_TUNING: u32 = 0;
pub const AL_VOCAL_MORPHER_PHONEME_A: u32 = 0;
pub const AL_VOCAL_MORPHER_PHONEME_E: u32 = 1;
pub const AL_VOCAL_MORPHER_PHONEME_I: u32 = 2;
pub const AL_VOCAL_MORPHER_PHONEME_O: u32 = 3;
pub const AL_VOCAL_MORPHER_PHONEME_U: u32 = 4;
pub const AL_VOCAL_MORPHER_PHONEME_AA: u32 = 5;
pub const AL_VOCAL_MORPHER_PHONEME_AE: u32 = 6;
pub const AL_VOCAL_MORPHER_PHONEME_AH: u32 = 7;
pub const AL_VOCAL_MORPHER_PHONEME_AO: u32 = 8;
pub const AL_VOCAL_MORPHER_PHONEME_EH: u32 = 9;
pub const AL_VOCAL_MORPHER_PHONEME_ER: u32 = 10;
pub const AL_VOCAL_MORPHER_PHONEME_IH: u32 = 11;
pub const AL_VOCAL_MORPHER_PHONEME_IY: u32 = 12;
pub const AL_VOCAL_MORPHER_PHONEME_UH: u32 = 13;
pub const AL_VOCAL_MORPHER_PHONEME_UW: u32 = 14;
pub const AL_VOCAL_MORPHER_PHONEME_B: u32 = 15;
pub const AL_VOCAL_MORPHER_PHONEME_D: u32 = 16;
pub const AL_VOCAL_MORPHER_PHONEME_F: u32 = 17;
pub const AL_VOCAL_MORPHER_PHONEME_G: u32 = 18;
pub const AL_VOCAL_MORPHER_PHONEME_J: u32 = 19;
pub const AL_VOCAL_MORPHER_PHONEME_K: u32 = 20;
pub const AL_VOCAL_MORPHER_PHONEME_L: u32 = 21;
pub const AL_VOCAL_MORPHER_PHONEME_M: u32 = 22;
pub const AL_VOCAL_MORPHER_PHONEME_N: u32 = 23;
pub const AL_VOCAL_MORPHER_PHONEME_P: u32 = 24;
pub const AL_VOCAL_MORPHER_PHONEME_R: u32 = 25;
pub const AL_VOCAL_MORPHER_PHONEME_S: u32 = 26;
pub const AL_VOCAL_MORPHER_PHONEME_T: u32 = 27;
pub const AL_VOCAL_MORPHER_PHONEME_V: u32 = 28;
pub const AL_VOCAL_MORPHER_PHONEME_Z: u32 = 29;
pub const AL_VOCAL_MORPHER_WAVEFORM_SINUSOID: u32 = 0;
pub const AL_VOCAL_MORPHER_WAVEFORM_TRIANGLE: u32 = 1;
pub const AL_VOCAL_MORPHER_WAVEFORM_SAWTOOTH: u32 = 2;
pub const AL_VOCAL_MORPHER_MIN_WAVEFORM: u32 = 0;
pub const AL_VOCAL_MORPHER_MAX_WAVEFORM: u32 = 2;
pub const AL_VOCAL_MORPHER_DEFAULT_WAVEFORM: u32 = 0;
pub const AL_VOCAL_MORPHER_MIN_RATE: f64 = 0.0;
pub const AL_VOCAL_MORPHER_MAX_RATE: f64 = 10.0;
pub const AL_VOCAL_MORPHER_DEFAULT_RATE: f64 = 1.41;
pub const AL_PITCH_SHIFTER_MIN_COARSE_TUNE: i32 = -12;
pub const AL_PITCH_SHIFTER_MAX_COARSE_TUNE: u32 = 12;
pub const AL_PITCH_SHIFTER_DEFAULT_COARSE_TUNE: u32 = 12;
pub const AL_PITCH_SHIFTER_MIN_FINE_TUNE: i32 = -50;
pub const AL_PITCH_SHIFTER_MAX_FINE_TUNE: u32 = 50;
pub const AL_PITCH_SHIFTER_DEFAULT_FINE_TUNE: u32 = 0;
pub const AL_RING_MODULATOR_MIN_FREQUENCY: f64 = 0.0;
pub const AL_RING_MODULATOR_MAX_FREQUENCY: f64 = 8000.0;
pub const AL_RING_MODULATOR_DEFAULT_FREQUENCY: f64 = 440.0;
pub const AL_RING_MODULATOR_MIN_HIGHPASS_CUTOFF: f64 = 0.0;
pub const AL_RING_MODULATOR_MAX_HIGHPASS_CUTOFF: f64 = 24000.0;
pub const AL_RING_MODULATOR_DEFAULT_HIGHPASS_CUTOFF: f64 = 800.0;
pub const AL_RING_MODULATOR_SINUSOID: u32 = 0;
pub const AL_RING_MODULATOR_SAWTOOTH: u32 = 1;
pub const AL_RING_MODULATOR_SQUARE: u32 = 2;
pub const AL_RING_MODULATOR_MIN_WAVEFORM: u32 = 0;
pub const AL_RING_MODULATOR_MAX_WAVEFORM: u32 = 2;
pub const AL_RING_MODULATOR_DEFAULT_WAVEFORM: u32 = 0;
pub const AL_AUTOWAH_MIN_ATTACK_TIME: f64 = 0.0001;
pub const AL_AUTOWAH_MAX_ATTACK_TIME: f64 = 1.0;
pub const AL_AUTOWAH_DEFAULT_ATTACK_TIME: f64 = 0.06;
pub const AL_AUTOWAH_MIN_RELEASE_TIME: f64 = 0.0001;
pub const AL_AUTOWAH_MAX_RELEASE_TIME: f64 = 1.0;
pub const AL_AUTOWAH_DEFAULT_RELEASE_TIME: f64 = 0.06;
pub const AL_AUTOWAH_MIN_RESONANCE: f64 = 2.0;
pub const AL_AUTOWAH_MAX_RESONANCE: f64 = 1000.0;
pub const AL_AUTOWAH_DEFAULT_RESONANCE: f64 = 1000.0;
pub const AL_AUTOWAH_MIN_PEAK_GAIN: f64 = 0.00003;
pub const AL_AUTOWAH_MAX_PEAK_GAIN: f64 = 31621.0;
pub const AL_AUTOWAH_DEFAULT_PEAK_GAIN: f64 = 11.22;
pub const AL_COMPRESSOR_MIN_ONOFF: u32 = 0;
pub const AL_COMPRESSOR_MAX_ONOFF: u32 = 1;
pub const AL_COMPRESSOR_DEFAULT_ONOFF: u32 = 1;
pub const AL_EQUALIZER_MIN_LOW_GAIN: f64 = 0.126;
pub const AL_EQUALIZER_MAX_LOW_GAIN: f64 = 7.943;
pub const AL_EQUALIZER_DEFAULT_LOW_GAIN: f64 = 1.0;
pub const AL_EQUALIZER_MIN_LOW_CUTOFF: f64 = 50.0;
pub const AL_EQUALIZER_MAX_LOW_CUTOFF: f64 = 800.0;
pub const AL_EQUALIZER_DEFAULT_LOW_CUTOFF: f64 = 200.0;
pub const AL_EQUALIZER_MIN_MID1_GAIN: f64 = 0.126;
pub const AL_EQUALIZER_MAX_MID1_GAIN: f64 = 7.943;
pub const AL_EQUALIZER_DEFAULT_MID1_GAIN: f64 = 1.0;
pub const AL_EQUALIZER_MIN_MID1_CENTER: f64 = 200.0;
pub const AL_EQUALIZER_MAX_MID1_CENTER: f64 = 3000.0;
pub const AL_EQUALIZER_DEFAULT_MID1_CENTER: f64 = 500.0;
pub const AL_EQUALIZER_MIN_MID1_WIDTH: f64 = 0.01;
pub const AL_EQUALIZER_MAX_MID1_WIDTH: f64 = 1.0;
pub const AL_EQUALIZER_DEFAULT_MID1_WIDTH: f64 = 1.0;
pub const AL_EQUALIZER_MIN_MID2_GAIN: f64 = 0.126;
pub const AL_EQUALIZER_MAX_MID2_GAIN: f64 = 7.943;
pub const AL_EQUALIZER_DEFAULT_MID2_GAIN: f64 = 1.0;
pub const AL_EQUALIZER_MIN_MID2_CENTER: f64 = 1000.0;
pub const AL_EQUALIZER_MAX_MID2_CENTER: f64 = 8000.0;
pub const AL_EQUALIZER_DEFAULT_MID2_CENTER: f64 = 3000.0;
pub const AL_EQUALIZER_MIN_MID2_WIDTH: f64 = 0.01;
pub const AL_EQUALIZER_MAX_MID2_WIDTH: f64 = 1.0;
pub const AL_EQUALIZER_DEFAULT_MID2_WIDTH: f64 = 1.0;
pub const AL_EQUALIZER_MIN_HIGH_GAIN: f64 = 0.126;
pub const AL_EQUALIZER_MAX_HIGH_GAIN: f64 = 7.943;
pub const AL_EQUALIZER_DEFAULT_HIGH_GAIN: f64 = 1.0;
pub const AL_EQUALIZER_MIN_HIGH_CUTOFF: f64 = 4000.0;
pub const AL_EQUALIZER_MAX_HIGH_CUTOFF: f64 = 16000.0;
pub const AL_EQUALIZER_DEFAULT_HIGH_CUTOFF: f64 = 6000.0;
pub const AL_MIN_AIR_ABSORPTION_FACTOR: f64 = 0.0;
pub const AL_MAX_AIR_ABSORPTION_FACTOR: f64 = 10.0;
pub const AL_DEFAULT_AIR_ABSORPTION_FACTOR: f64 = 0.0;
pub const AL_MIN_ROOM_ROLLOFF_FACTOR: f64 = 0.0;
pub const AL_MAX_ROOM_ROLLOFF_FACTOR: f64 = 10.0;
pub const AL_DEFAULT_ROOM_ROLLOFF_FACTOR: f64 = 0.0;
pub const AL_MIN_CONE_OUTER_GAINHF: f64 = 0.0;
pub const AL_MAX_CONE_OUTER_GAINHF: f64 = 1.0;
pub const AL_DEFAULT_CONE_OUTER_GAINHF: f64 = 1.0;
pub const AL_MIN_DIRECT_FILTER_GAINHF_AUTO: u32 = 0;
pub const AL_MAX_DIRECT_FILTER_GAINHF_AUTO: u32 = 1;
pub const AL_DEFAULT_DIRECT_FILTER_GAINHF_AUTO: u32 = 1;
pub const AL_MIN_AUXILIARY_SEND_FILTER_GAIN_AUTO: u32 = 0;
pub const AL_MAX_AUXILIARY_SEND_FILTER_GAIN_AUTO: u32 = 1;
pub const AL_DEFAULT_AUXILIARY_SEND_FILTER_GAIN_AUTO: u32 = 1;
pub const AL_MIN_AUXILIARY_SEND_FILTER_GAINHF_AUTO: u32 = 0;
pub const AL_MAX_AUXILIARY_SEND_FILTER_GAINHF_AUTO: u32 = 1;
pub const AL_DEFAULT_AUXILIARY_SEND_FILTER_GAINHF_AUTO: u32 = 1;
pub const AL_DEFAULT_METERS_PER_UNIT: f64 = 1.0;
pub type va_list = *mut ::std::os::raw::c_char;
extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type __vcrt_bool = bool;
pub type wchar_t = ::std::os::raw::c_ushort;
extern "C" {
    pub fn __security_init_cookie();
}
extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize) -> !;
}
extern "C" {
    pub static mut __security_cookie: usize;
}
pub type __crt_bool = bool;
extern "C" {
    pub fn _invalid_parameter_noinfo();
}
extern "C" {
    pub fn _invalid_parameter_noinfo_noreturn() -> !;
}
extern "C" {
    pub fn _invoke_watson(
        _Expression: *const wchar_t,
        _FunctionName: *const wchar_t,
        _FileName: *const wchar_t,
        _LineNo: ::std::os::raw::c_uint,
        _Reserved: usize
    ) -> !;
}
pub type errno_t = ::std::os::raw::c_int;
pub type wint_t = ::std::os::raw::c_ushort;
pub type wctype_t = ::std::os::raw::c_ushort;
pub type __time32_t = ::std::os::raw::c_long;
pub type __time64_t = ::std::os::raw::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data_public {
    pub _locale_pctype: *const ::std::os::raw::c_ushort,
    pub _locale_mb_cur_max: ::std::os::raw::c_int,
    pub _locale_lc_codepage: ::std::os::raw::c_uint
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __crt_locale_data_public"]
        [::std::mem::size_of::<__crt_locale_data_public>() - 16usize];
    ["Alignment of __crt_locale_data_public"]
        [::std::mem::align_of::<__crt_locale_data_public>() - 8usize];
    ["Offset of field: __crt_locale_data_public::_locale_pctype"]
        [::std::mem::offset_of!(__crt_locale_data_public, _locale_pctype) - 0usize];
    ["Offset of field: __crt_locale_data_public::_locale_mb_cur_max"]
        [::std::mem::offset_of!(__crt_locale_data_public, _locale_mb_cur_max) - 8usize];
    ["Offset of field: __crt_locale_data_public::_locale_lc_codepage"]
        [::std::mem::offset_of!(__crt_locale_data_public, _locale_lc_codepage) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_pointers {
    pub locinfo: *mut __crt_locale_data,
    pub mbcinfo: *mut __crt_multibyte_data
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __crt_locale_pointers"][::std::mem::size_of::<__crt_locale_pointers>() - 16usize];
    ["Alignment of __crt_locale_pointers"]
        [::std::mem::align_of::<__crt_locale_pointers>() - 8usize];
    ["Offset of field: __crt_locale_pointers::locinfo"]
        [::std::mem::offset_of!(__crt_locale_pointers, locinfo) - 0usize];
    ["Offset of field: __crt_locale_pointers::mbcinfo"]
        [::std::mem::offset_of!(__crt_locale_pointers, mbcinfo) - 8usize];
};
pub type _locale_t = *mut __crt_locale_pointers;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Mbstatet {
    pub _Wchar: ::std::os::raw::c_ulong,
    pub _Byte: ::std::os::raw::c_ushort,
    pub _State: ::std::os::raw::c_ushort
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Mbstatet"][::std::mem::size_of::<_Mbstatet>() - 8usize];
    ["Alignment of _Mbstatet"][::std::mem::align_of::<_Mbstatet>() - 4usize];
    ["Offset of field: _Mbstatet::_Wchar"][::std::mem::offset_of!(_Mbstatet, _Wchar) - 0usize];
    ["Offset of field: _Mbstatet::_Byte"][::std::mem::offset_of!(_Mbstatet, _Byte) - 4usize];
    ["Offset of field: _Mbstatet::_State"][::std::mem::offset_of!(_Mbstatet, _State) - 6usize];
};
pub type mbstate_t = _Mbstatet;
pub type time_t = __time64_t;
pub type rsize_t = usize;
extern "C" {
    pub fn _clearfp() -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn _controlfp(
        _NewValue: ::std::os::raw::c_uint,
        _Mask: ::std::os::raw::c_uint
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn _set_controlfp(_NewValue: ::std::os::raw::c_uint, _Mask: ::std::os::raw::c_uint);
}
extern "C" {
    pub fn _controlfp_s(
        _CurrentState: *mut ::std::os::raw::c_uint,
        _NewValue: ::std::os::raw::c_uint,
        _Mask: ::std::os::raw::c_uint
    ) -> errno_t;
}
extern "C" {
    pub fn _statusfp() -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn _fpreset();
}
extern "C" {
    pub fn _control87(
        _NewValue: ::std::os::raw::c_uint,
        _Mask: ::std::os::raw::c_uint
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn __fpecode() -> *mut ::std::os::raw::c_int;
}
extern "C" {
    pub fn __fpe_flt_rounds() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _copysign(_Number: f64, _Sign: f64) -> f64;
}
extern "C" {
    pub fn _chgsign(_X: f64) -> f64;
}
extern "C" {
    pub fn _scalb(_X: f64, _Y: ::std::os::raw::c_long) -> f64;
}
extern "C" {
    pub fn _logb(_X: f64) -> f64;
}
extern "C" {
    pub fn _nextafter(_X: f64, _Y: f64) -> f64;
}
extern "C" {
    pub fn _finite(_X: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _isnan(_X: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _fpclass(_X: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _scalbf(_X: f32, _Y: ::std::os::raw::c_long) -> f32;
}
extern "C" {
    pub fn fpreset();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ALCdevice {
    _unused: [u8; 0]
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ALCcontext {
    _unused: [u8; 0]
}
/// 8-bit boolean
pub type ALCboolean = ::std::os::raw::c_char;
/// character
pub type ALCchar = ::std::os::raw::c_char;
/// signed 8-bit integer
pub type ALCbyte = ::std::os::raw::c_schar;
/// unsigned 8-bit integer
pub type ALCubyte = ::std::os::raw::c_uchar;
/// signed 16-bit integer
pub type ALCshort = ::std::os::raw::c_short;
/// unsigned 16-bit integer
pub type ALCushort = ::std::os::raw::c_ushort;
/// signed 32-bit integer
pub type ALCint = ::std::os::raw::c_int;
/// unsigned 32-bit integer
pub type ALCuint = ::std::os::raw::c_uint;
/// non-negative 32-bit integer size
pub type ALCsizei = ::std::os::raw::c_int;
/// 32-bit enumeration value
pub type ALCenum = ::std::os::raw::c_int;
/// 32-bit IEEE-754 floating-point
pub type ALCfloat = f32;
/// 64-bit IEEE-754 floating-point
pub type ALCdouble = f64;
/// void type (for opaque pointers only)
pub type ALCvoid = ::std::os::raw::c_void;
extern "C" {
    /// Create and attach a context to the given device.
    pub fn alcCreateContext(device: *mut ALCdevice, attrlist: *const ALCint) -> *mut ALCcontext;
}
extern "C" {
    /// Makes the given context the active process-wide context. Passing NULL clears
    /// the active context.
    pub fn alcMakeContextCurrent(context: *mut ALCcontext) -> ALCboolean;
}
extern "C" {
    /// Resumes processing updates for the given context.
    pub fn alcProcessContext(context: *mut ALCcontext);
}
extern "C" {
    /// Suspends updates for the given context.
    pub fn alcSuspendContext(context: *mut ALCcontext);
}
extern "C" {
    /// Remove a context from its device and destroys it.
    pub fn alcDestroyContext(context: *mut ALCcontext);
}
extern "C" {
    /// Returns the currently active context.
    pub fn alcGetCurrentContext() -> *mut ALCcontext;
}
extern "C" {
    /// Returns the device that a particular context is attached to.
    pub fn alcGetContextsDevice(context: *mut ALCcontext) -> *mut ALCdevice;
}
extern "C" {
    /// Opens the named playback device.
    pub fn alcOpenDevice(devicename: *const ALCchar) -> *mut ALCdevice;
}
extern "C" {
    /// Closes the given playback device.
    pub fn alcCloseDevice(device: *mut ALCdevice) -> ALCboolean;
}
extern "C" {
    /// Obtain the most recent Device error.
    pub fn alcGetError(device: *mut ALCdevice) -> ALCenum;
}
extern "C" {
    /// Query for the presence of an extension on the device. Pass a NULL device to
    /// query a device-inspecific extension.
    pub fn alcIsExtensionPresent(device: *mut ALCdevice, extname: *const ALCchar) -> ALCboolean;
}
extern "C" {
    /// Retrieve the address of a function. Given a non-NULL device, the returned
    /// function may be device-specific.
    pub fn alcGetProcAddress(device: *mut ALCdevice, funcname: *const ALCchar) -> *mut ALCvoid;
}
extern "C" {
    /// Retrieve the value of an enum. Given a non-NULL device, the returned value
    /// may be device-specific.
    pub fn alcGetEnumValue(device: *mut ALCdevice, enumname: *const ALCchar) -> ALCenum;
}
extern "C" {
    /// Returns information about the device, and error strings.
    pub fn alcGetString(device: *mut ALCdevice, param: ALCenum) -> *const ALCchar;
}
extern "C" {
    /// Returns information about the device and the version of OpenAL.
    pub fn alcGetIntegerv(
        device: *mut ALCdevice,
        param: ALCenum,
        size: ALCsizei,
        values: *mut ALCint
    );
}
extern "C" {
    /// Opens the named capture device with the given frequency, format, and buffer
    /// size.
    pub fn alcCaptureOpenDevice(
        devicename: *const ALCchar,
        frequency: ALCuint,
        format: ALCenum,
        buffersize: ALCsizei
    ) -> *mut ALCdevice;
}
extern "C" {
    /// Closes the given capture device.
    pub fn alcCaptureCloseDevice(device: *mut ALCdevice) -> ALCboolean;
}
extern "C" {
    /// Starts capturing samples into the device buffer.
    pub fn alcCaptureStart(device: *mut ALCdevice);
}
extern "C" {
    /// Stops capturing samples. Samples in the device buffer remain available.
    pub fn alcCaptureStop(device: *mut ALCdevice);
}
extern "C" {
    /// Reads samples from the device buffer.
    pub fn alcCaptureSamples(device: *mut ALCdevice, buffer: *mut ALCvoid, samples: ALCsizei);
}
pub type LPALCCREATECONTEXT = ::std::option::Option<
    unsafe extern "C" fn(device: *mut ALCdevice, attrlist: *const ALCint) -> *mut ALCcontext
>;
pub type LPALCMAKECONTEXTCURRENT =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext) -> ALCboolean>;
pub type LPALCPROCESSCONTEXT =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)>;
pub type LPALCSUSPENDCONTEXT =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)>;
pub type LPALCDESTROYCONTEXT =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext)>;
pub type LPALCGETCURRENTCONTEXT = ::std::option::Option<unsafe extern "C" fn() -> *mut ALCcontext>;
pub type LPALCGETCONTEXTSDEVICE =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ALCcontext) -> *mut ALCdevice>;
pub type LPALCOPENDEVICE =
    ::std::option::Option<unsafe extern "C" fn(devicename: *const ALCchar) -> *mut ALCdevice>;
pub type LPALCCLOSEDEVICE =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice) -> ALCboolean>;
pub type LPALCGETERROR =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice) -> ALCenum>;
pub type LPALCISEXTENSIONPRESENT = ::std::option::Option<
    unsafe extern "C" fn(device: *mut ALCdevice, extname: *const ALCchar) -> ALCboolean
>;
pub type LPALCGETPROCADDRESS = ::std::option::Option<
    unsafe extern "C" fn(device: *mut ALCdevice, funcname: *const ALCchar) -> *mut ALCvoid
>;
pub type LPALCGETENUMVALUE = ::std::option::Option<
    unsafe extern "C" fn(device: *mut ALCdevice, enumname: *const ALCchar) -> ALCenum
>;
pub type LPALCGETSTRING = ::std::option::Option<
    unsafe extern "C" fn(device: *mut ALCdevice, param: ALCenum) -> *const ALCchar
>;
pub type LPALCGETINTEGERV = ::std::option::Option<
    unsafe extern "C" fn(
        device: *mut ALCdevice,
        param: ALCenum,
        size: ALCsizei,
        values: *mut ALCint
    )
>;
pub type LPALCCAPTUREOPENDEVICE = ::std::option::Option<
    unsafe extern "C" fn(
        devicename: *const ALCchar,
        frequency: ALCuint,
        format: ALCenum,
        buffersize: ALCsizei
    ) -> *mut ALCdevice
>;
pub type LPALCCAPTURECLOSEDEVICE =
    ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice) -> ALCboolean>;
pub type LPALCCAPTURESTART = ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCCAPTURESTOP = ::std::option::Option<unsafe extern "C" fn(device: *mut ALCdevice)>;
pub type LPALCCAPTURESAMPLES = ::std::option::Option<
    unsafe extern "C" fn(device: *mut ALCdevice, buffer: *mut ALCvoid, samples: ALCsizei)
>;
/// 8-bit boolean
pub type ALboolean = ::std::os::raw::c_char;
/// character
pub type ALchar = ::std::os::raw::c_char;
/// signed 8-bit integer
pub type ALbyte = ::std::os::raw::c_schar;
/// unsigned 8-bit integer
pub type ALubyte = ::std::os::raw::c_uchar;
/// signed 16-bit integer
pub type ALshort = ::std::os::raw::c_short;
/// unsigned 16-bit integer
pub type ALushort = ::std::os::raw::c_ushort;
/// signed 32-bit integer
pub type ALint = ::std::os::raw::c_int;
/// unsigned 32-bit integer
pub type ALuint = ::std::os::raw::c_uint;
/// non-negative 32-bit integer size
pub type ALsizei = ::std::os::raw::c_int;
/// 32-bit enumeration value
pub type ALenum = ::std::os::raw::c_int;
/// 32-bit IEEE-754 floating-point
pub type ALfloat = f32;
/// 64-bit IEEE-754 floating-point
pub type ALdouble = f64;
/// void type (opaque pointers only)
pub type ALvoid = ::std::os::raw::c_void;
extern "C" {
    pub fn alEnable(capability: ALenum);
}
extern "C" {
    pub fn alDisable(capability: ALenum);
}
extern "C" {
    pub fn alIsEnabled(capability: ALenum) -> ALboolean;
}
extern "C" {
    pub fn alDopplerFactor(value: ALfloat);
}
extern "C" {
    pub fn alDopplerVelocity(value: ALfloat);
}
extern "C" {
    pub fn alSpeedOfSound(value: ALfloat);
}
extern "C" {
    pub fn alDistanceModel(distanceModel: ALenum);
}
extern "C" {
    pub fn alGetString(param: ALenum) -> *const ALchar;
}
extern "C" {
    pub fn alGetBooleanv(param: ALenum, values: *mut ALboolean);
}
extern "C" {
    pub fn alGetIntegerv(param: ALenum, values: *mut ALint);
}
extern "C" {
    pub fn alGetFloatv(param: ALenum, values: *mut ALfloat);
}
extern "C" {
    pub fn alGetDoublev(param: ALenum, values: *mut ALdouble);
}
extern "C" {
    pub fn alGetBoolean(param: ALenum) -> ALboolean;
}
extern "C" {
    pub fn alGetInteger(param: ALenum) -> ALint;
}
extern "C" {
    pub fn alGetFloat(param: ALenum) -> ALfloat;
}
extern "C" {
    pub fn alGetDouble(param: ALenum) -> ALdouble;
}
extern "C" {
    /// Obtain the first error generated in the AL context since the last call to
    /// this function.
    pub fn alGetError() -> ALenum;
}
extern "C" {
    /// Query for the presence of an extension on the AL context.
    pub fn alIsExtensionPresent(extname: *const ALchar) -> ALboolean;
}
extern "C" {
    /// Retrieve the address of a function. The returned function may be context-
    /// specific.
    pub fn alGetProcAddress(fname: *const ALchar) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    /// Retrieve the value of an enum. The returned value may be context-specific.
    pub fn alGetEnumValue(ename: *const ALchar) -> ALenum;
}
extern "C" {
    pub fn alListenerf(param: ALenum, value: ALfloat);
}
extern "C" {
    pub fn alListener3f(param: ALenum, value1: ALfloat, value2: ALfloat, value3: ALfloat);
}
extern "C" {
    pub fn alListenerfv(param: ALenum, values: *const ALfloat);
}
extern "C" {
    pub fn alListeneri(param: ALenum, value: ALint);
}
extern "C" {
    pub fn alListener3i(param: ALenum, value1: ALint, value2: ALint, value3: ALint);
}
extern "C" {
    pub fn alListeneriv(param: ALenum, values: *const ALint);
}
extern "C" {
    pub fn alGetListenerf(param: ALenum, value: *mut ALfloat);
}
extern "C" {
    pub fn alGetListener3f(
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    );
}
extern "C" {
    pub fn alGetListenerfv(param: ALenum, values: *mut ALfloat);
}
extern "C" {
    pub fn alGetListeneri(param: ALenum, value: *mut ALint);
}
extern "C" {
    pub fn alGetListener3i(
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    );
}
extern "C" {
    pub fn alGetListeneriv(param: ALenum, values: *mut ALint);
}
extern "C" {
    /// Create source objects.
    pub fn alGenSources(n: ALsizei, sources: *mut ALuint);
}
extern "C" {
    /// Delete source objects.
    pub fn alDeleteSources(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /// Verify an ID is for a valid source.
    pub fn alIsSource(source: ALuint) -> ALboolean;
}
extern "C" {
    pub fn alSourcef(source: ALuint, param: ALenum, value: ALfloat);
}
extern "C" {
    pub fn alSource3f(
        source: ALuint,
        param: ALenum,
        value1: ALfloat,
        value2: ALfloat,
        value3: ALfloat
    );
}
extern "C" {
    pub fn alSourcefv(source: ALuint, param: ALenum, values: *const ALfloat);
}
extern "C" {
    pub fn alSourcei(source: ALuint, param: ALenum, value: ALint);
}
extern "C" {
    pub fn alSource3i(source: ALuint, param: ALenum, value1: ALint, value2: ALint, value3: ALint);
}
extern "C" {
    pub fn alSourceiv(source: ALuint, param: ALenum, values: *const ALint);
}
extern "C" {
    pub fn alGetSourcef(source: ALuint, param: ALenum, value: *mut ALfloat);
}
extern "C" {
    pub fn alGetSource3f(
        source: ALuint,
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    );
}
extern "C" {
    pub fn alGetSourcefv(source: ALuint, param: ALenum, values: *mut ALfloat);
}
extern "C" {
    pub fn alGetSourcei(source: ALuint, param: ALenum, value: *mut ALint);
}
extern "C" {
    pub fn alGetSource3i(
        source: ALuint,
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    );
}
extern "C" {
    pub fn alGetSourceiv(source: ALuint, param: ALenum, values: *mut ALint);
}
extern "C" {
    /// Play, restart, or resume a source, setting its state to AL_PLAYING.
    pub fn alSourcePlay(source: ALuint);
}
extern "C" {
    /// Stop a source, setting its state to AL_STOPPED if playing or paused.
    pub fn alSourceStop(source: ALuint);
}
extern "C" {
    /// Rewind a source, setting its state to AL_INITIAL.
    pub fn alSourceRewind(source: ALuint);
}
extern "C" {
    /// Pause a source, setting its state to AL_PAUSED if playing.
    pub fn alSourcePause(source: ALuint);
}
extern "C" {
    /// Play, restart, or resume a list of sources atomically.
    pub fn alSourcePlayv(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /// Stop a list of sources atomically.
    pub fn alSourceStopv(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /// Rewind a list of sources atomically.
    pub fn alSourceRewindv(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /// Pause a list of sources atomically.
    pub fn alSourcePausev(n: ALsizei, sources: *const ALuint);
}
extern "C" {
    /// Queue buffers onto a source
    pub fn alSourceQueueBuffers(source: ALuint, nb: ALsizei, buffers: *const ALuint);
}
extern "C" {
    /// Unqueue processed buffers from a source
    pub fn alSourceUnqueueBuffers(source: ALuint, nb: ALsizei, buffers: *mut ALuint);
}
extern "C" {
    /// Create buffer objects
    pub fn alGenBuffers(n: ALsizei, buffers: *mut ALuint);
}
extern "C" {
    /// Delete buffer objects
    pub fn alDeleteBuffers(n: ALsizei, buffers: *const ALuint);
}
extern "C" {
    /// Verify an ID is a valid buffer (including the NULL buffer)
    pub fn alIsBuffer(buffer: ALuint) -> ALboolean;
}
extern "C" {
    /// Copies data into the buffer, interpreting it using the specified format and
    /// samplerate.
    pub fn alBufferData(
        buffer: ALuint,
        format: ALenum,
        data: *const ALvoid,
        size: ALsizei,
        samplerate: ALsizei
    );
}
extern "C" {
    pub fn alBufferf(buffer: ALuint, param: ALenum, value: ALfloat);
}
extern "C" {
    pub fn alBuffer3f(
        buffer: ALuint,
        param: ALenum,
        value1: ALfloat,
        value2: ALfloat,
        value3: ALfloat
    );
}
extern "C" {
    pub fn alBufferfv(buffer: ALuint, param: ALenum, values: *const ALfloat);
}
extern "C" {
    pub fn alBufferi(buffer: ALuint, param: ALenum, value: ALint);
}
extern "C" {
    pub fn alBuffer3i(buffer: ALuint, param: ALenum, value1: ALint, value2: ALint, value3: ALint);
}
extern "C" {
    pub fn alBufferiv(buffer: ALuint, param: ALenum, values: *const ALint);
}
extern "C" {
    pub fn alGetBufferf(buffer: ALuint, param: ALenum, value: *mut ALfloat);
}
extern "C" {
    pub fn alGetBuffer3f(
        buffer: ALuint,
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    );
}
extern "C" {
    pub fn alGetBufferfv(buffer: ALuint, param: ALenum, values: *mut ALfloat);
}
extern "C" {
    pub fn alGetBufferi(buffer: ALuint, param: ALenum, value: *mut ALint);
}
extern "C" {
    pub fn alGetBuffer3i(
        buffer: ALuint,
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    );
}
extern "C" {
    pub fn alGetBufferiv(buffer: ALuint, param: ALenum, values: *mut ALint);
}
pub type LPALENABLE = ::std::option::Option<unsafe extern "C" fn(capability: ALenum)>;
pub type LPALDISABLE = ::std::option::Option<unsafe extern "C" fn(capability: ALenum)>;
pub type LPALISENABLED =
    ::std::option::Option<unsafe extern "C" fn(capability: ALenum) -> ALboolean>;
pub type LPALGETSTRING =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> *const ALchar>;
pub type LPALGETBOOLEANV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALboolean)>;
pub type LPALGETINTEGERV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALint)>;
pub type LPALGETFLOATV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALfloat)>;
pub type LPALGETDOUBLEV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALdouble)>;
pub type LPALGETBOOLEAN = ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALboolean>;
pub type LPALGETINTEGER = ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALint>;
pub type LPALGETFLOAT = ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALfloat>;
pub type LPALGETDOUBLE = ::std::option::Option<unsafe extern "C" fn(param: ALenum) -> ALdouble>;
pub type LPALGETERROR = ::std::option::Option<unsafe extern "C" fn() -> ALenum>;
pub type LPALISEXTENSIONPRESENT =
    ::std::option::Option<unsafe extern "C" fn(extname: *const ALchar) -> ALboolean>;
pub type LPALGETPROCADDRESS = ::std::option::Option<
    unsafe extern "C" fn(fname: *const ALchar) -> *mut ::std::os::raw::c_void
>;
pub type LPALGETENUMVALUE =
    ::std::option::Option<unsafe extern "C" fn(ename: *const ALchar) -> ALenum>;
pub type LPALLISTENERF = ::std::option::Option<unsafe extern "C" fn(param: ALenum, value: ALfloat)>;
pub type LPALLISTENER3F = ::std::option::Option<
    unsafe extern "C" fn(param: ALenum, value1: ALfloat, value2: ALfloat, value3: ALfloat)
>;
pub type LPALLISTENERFV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *const ALfloat)>;
pub type LPALLISTENERI = ::std::option::Option<unsafe extern "C" fn(param: ALenum, value: ALint)>;
pub type LPALLISTENER3I = ::std::option::Option<
    unsafe extern "C" fn(param: ALenum, value1: ALint, value2: ALint, value3: ALint)
>;
pub type LPALLISTENERIV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *const ALint)>;
pub type LPALGETLISTENERF =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, value: *mut ALfloat)>;
pub type LPALGETLISTENER3F = ::std::option::Option<
    unsafe extern "C" fn(
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    )
>;
pub type LPALGETLISTENERFV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALfloat)>;
pub type LPALGETLISTENERI =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, value: *mut ALint)>;
pub type LPALGETLISTENER3I = ::std::option::Option<
    unsafe extern "C" fn(param: ALenum, value1: *mut ALint, value2: *mut ALint, value3: *mut ALint)
>;
pub type LPALGETLISTENERIV =
    ::std::option::Option<unsafe extern "C" fn(param: ALenum, values: *mut ALint)>;
pub type LPALGENSOURCES =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *mut ALuint)>;
pub type LPALDELETESOURCES =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALISSOURCE = ::std::option::Option<unsafe extern "C" fn(source: ALuint) -> ALboolean>;
pub type LPALSOURCEF =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, value: ALfloat)>;
pub type LPALSOURCE3F = ::std::option::Option<
    unsafe extern "C" fn(
        source: ALuint,
        param: ALenum,
        value1: ALfloat,
        value2: ALfloat,
        value3: ALfloat
    )
>;
pub type LPALSOURCEFV = ::std::option::Option<
    unsafe extern "C" fn(source: ALuint, param: ALenum, values: *const ALfloat)
>;
pub type LPALSOURCEI =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, value: ALint)>;
pub type LPALSOURCE3I = ::std::option::Option<
    unsafe extern "C" fn(
        source: ALuint,
        param: ALenum,
        value1: ALint,
        value2: ALint,
        value3: ALint
    )
>;
pub type LPALSOURCEIV = ::std::option::Option<
    unsafe extern "C" fn(source: ALuint, param: ALenum, values: *const ALint)
>;
pub type LPALGETSOURCEF =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, value: *mut ALfloat)>;
pub type LPALGETSOURCE3F = ::std::option::Option<
    unsafe extern "C" fn(
        source: ALuint,
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    )
>;
pub type LPALGETSOURCEFV = ::std::option::Option<
    unsafe extern "C" fn(source: ALuint, param: ALenum, values: *mut ALfloat)
>;
pub type LPALGETSOURCEI =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, value: *mut ALint)>;
pub type LPALGETSOURCE3I = ::std::option::Option<
    unsafe extern "C" fn(
        source: ALuint,
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    )
>;
pub type LPALGETSOURCEIV =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, param: ALenum, values: *mut ALint)>;
pub type LPALSOURCEPLAYV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALSOURCESTOPV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALSOURCEREWINDV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALSOURCEPAUSEV =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, sources: *const ALuint)>;
pub type LPALSOURCEPLAY = ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCESTOP = ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCEREWIND = ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCEPAUSE = ::std::option::Option<unsafe extern "C" fn(source: ALuint)>;
pub type LPALSOURCEQUEUEBUFFERS = ::std::option::Option<
    unsafe extern "C" fn(source: ALuint, nb: ALsizei, buffers: *const ALuint)
>;
pub type LPALSOURCEUNQUEUEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(source: ALuint, nb: ALsizei, buffers: *mut ALuint)>;
pub type LPALGENBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, buffers: *mut ALuint)>;
pub type LPALDELETEBUFFERS =
    ::std::option::Option<unsafe extern "C" fn(n: ALsizei, buffers: *const ALuint)>;
pub type LPALISBUFFER = ::std::option::Option<unsafe extern "C" fn(buffer: ALuint) -> ALboolean>;
pub type LPALBUFFERDATA = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        format: ALenum,
        data: *const ALvoid,
        size: ALsizei,
        samplerate: ALsizei
    )
>;
pub type LPALBUFFERF =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, value: ALfloat)>;
pub type LPALBUFFER3F = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        param: ALenum,
        value1: ALfloat,
        value2: ALfloat,
        value3: ALfloat
    )
>;
pub type LPALBUFFERFV = ::std::option::Option<
    unsafe extern "C" fn(buffer: ALuint, param: ALenum, values: *const ALfloat)
>;
pub type LPALBUFFERI =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, value: ALint)>;
pub type LPALBUFFER3I = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        param: ALenum,
        value1: ALint,
        value2: ALint,
        value3: ALint
    )
>;
pub type LPALBUFFERIV = ::std::option::Option<
    unsafe extern "C" fn(buffer: ALuint, param: ALenum, values: *const ALint)
>;
pub type LPALGETBUFFERF =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, value: *mut ALfloat)>;
pub type LPALGETBUFFER3F = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        param: ALenum,
        value1: *mut ALfloat,
        value2: *mut ALfloat,
        value3: *mut ALfloat
    )
>;
pub type LPALGETBUFFERFV = ::std::option::Option<
    unsafe extern "C" fn(buffer: ALuint, param: ALenum, values: *mut ALfloat)
>;
pub type LPALGETBUFFERI =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, value: *mut ALint)>;
pub type LPALGETBUFFER3I = ::std::option::Option<
    unsafe extern "C" fn(
        buffer: ALuint,
        param: ALenum,
        value1: *mut ALint,
        value2: *mut ALint,
        value3: *mut ALint
    )
>;
pub type LPALGETBUFFERIV =
    ::std::option::Option<unsafe extern "C" fn(buffer: ALuint, param: ALenum, values: *mut ALint)>;
pub type LPALDOPPLERFACTOR = ::std::option::Option<unsafe extern "C" fn(value: ALfloat)>;
pub type LPALDOPPLERVELOCITY = ::std::option::Option<unsafe extern "C" fn(value: ALfloat)>;
pub type LPALSPEEDOFSOUND = ::std::option::Option<unsafe extern "C" fn(value: ALfloat)>;
pub type LPALDISTANCEMODEL = ::std::option::Option<unsafe extern "C" fn(distanceModel: ALenum)>;
pub type LPALGENEFFECTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei, arg2: *mut ALuint)>;
pub type LPALDELETEEFFECTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei, arg2: *const ALuint)>;
pub type LPALISEFFECT = ::std::option::Option<unsafe extern "C" fn(arg1: ALuint) -> ALboolean>;
pub type LPALEFFECTI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: ALint)>;
pub type LPALEFFECTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *const ALint)>;
pub type LPALEFFECTF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: ALfloat)>;
pub type LPALEFFECTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *const ALfloat)>;
pub type LPALGETEFFECTI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALint)>;
pub type LPALGETEFFECTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALint)>;
pub type LPALGETEFFECTF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALfloat)>;
pub type LPALGETEFFECTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALfloat)>;
pub type LPALGENFILTERS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei, arg2: *mut ALuint)>;
pub type LPALDELETEFILTERS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei, arg2: *const ALuint)>;
pub type LPALISFILTER = ::std::option::Option<unsafe extern "C" fn(arg1: ALuint) -> ALboolean>;
pub type LPALFILTERI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: ALint)>;
pub type LPALFILTERIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *const ALint)>;
pub type LPALFILTERF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: ALfloat)>;
pub type LPALFILTERFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *const ALfloat)>;
pub type LPALGETFILTERI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALint)>;
pub type LPALGETFILTERIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALint)>;
pub type LPALGETFILTERF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALfloat)>;
pub type LPALGETFILTERFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALfloat)>;
pub type LPALGENAUXILIARYEFFECTSLOTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei, arg2: *mut ALuint)>;
pub type LPALDELETEAUXILIARYEFFECTSLOTS =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALsizei, arg2: *const ALuint)>;
pub type LPALISAUXILIARYEFFECTSLOT =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint) -> ALboolean>;
pub type LPALAUXILIARYEFFECTSLOTI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: ALint)>;
pub type LPALAUXILIARYEFFECTSLOTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *const ALint)>;
pub type LPALAUXILIARYEFFECTSLOTF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: ALfloat)>;
pub type LPALAUXILIARYEFFECTSLOTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *const ALfloat)>;
pub type LPALGETAUXILIARYEFFECTSLOTI =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALint)>;
pub type LPALGETAUXILIARYEFFECTSLOTIV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALint)>;
pub type LPALGETAUXILIARYEFFECTSLOTF =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALfloat)>;
pub type LPALGETAUXILIARYEFFECTSLOTFV =
    ::std::option::Option<unsafe extern "C" fn(arg1: ALuint, arg2: ALenum, arg3: *mut ALfloat)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data {
    pub _address: u8
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_multibyte_data {
    pub _address: u8
}
